### ISSUE TITLE
Style suggestion: consistent placing of structure item doc comments

### ISSUE THREAD

**Issue by CraigFe** [ocaml-ppx/ocamlformat#1010]
**What is the reason for this new style?**
Inconsistency surrounding doc comments and signatures. Consider the following example:

```ocaml
(** This comment goes before *)
module S_ext : sig
  type t
end

module Index : Index.S
(** This one goes after *)

module Index2
    (Paramater_module : BAR_LONG_MODULE_TYPE_NAME)
    (Foo : BAR)
    (Foo : BAR)
    (Foo : BAR)
    (Foo : BAR)
    (Foo : BAR) : sig end
(** This one _still_ goes after *)

module Make (Config : sig
  val blah : string

  (* this could be a really long signature *)
end) : S
(** Doc comment still goes after *)
```
With `profile=conventional`, Ocamlformat will try to put structure doc comments _after_ the struct by default (presumably to keep symmetry with the value signatures). When the structure is too large, it will instead put the comment at the start. I like this behaviour; however, it isn't consistent about this w.r.t. functors whose parameters span multiple lines.

**Describe the solution you'd like**
I see two solutions:
 1. always put doc comments on structures before, regardless of the size of the structure.
 1. refine the size heuristic to account for potential multi-line functor parameters.

CC. @Julow

**Comment by Julow** [comment]
Your 2nd suggestion is easy to implement but the inconsistency still remains.

We could get rid of this rule and:
- Always put doc comments before modules, as you suggested
  This would be inconsistent with `val`s, but at least every forms of `module` would be consistent
- Follow the `doc-comments=before|after` option strictly
  I think the argument against that is the comment would be too far down to be noticed.
  My opinion is that this comment is about how this module fits with the rest of the parent module and does not matter when reading the module implementation.
  ```ocaml
  module Foo = struct
    (** Implement that algorithm
        ... long comment *)

    type t = ...
  end
  (** This module is used represent x *)

  type t = { x : Foo.t }
  (** t *)
  ```

Also, there is an other special case, doc comments cannot be placed after a variant declaration:

```ocaml
type t = int
(** t *)

(** t' *)
type t' = Foo
```

Otherwise, the comment would be attached to the last constructor (by OCaml's parser) and the AST would change:

```diff
-type t' = Foo
-(** t' *)
+type t' = Foo  (** t' *)
```

**Comment by CraigFe** [comment]
I prefer the first option of the two you suggested, given that `doc-comments=after` is the default. I suspect in many cases the comment in the parent module will be just as long, if not longer, than the one at the top of the child module. (this is because the parent module must explain the context of the module). This is certainly the case in `irmin.mli` for instance:
 - https://github.com/mirage/irmin/blob/master/src/irmin/irmin.mli#L517
 - https://github.com/mirage/irmin/blob/master/src/irmin/irmin.mli#L767
 - https://github.com/mirage/irmin/blob/master/src/irmin/irmin.mli#L962

I have no idea how representative Irmin is, however :slightly_smiling_face: 

If you're keen to achieve strict accordance with the options (which I think is a good idea), you could split `doc-comments` into `doc-comments-{let,module}` (with different defaults in the conventional profile).

**Comment by emillon** [comment]
Should we close this now that `doc-comments` is being replaced by the more deterministic `doc-comments-val`? or should we wait that it's completely removed?

**Comment by Julow** [comment]
This issue is indeed fixed. I think changing the default behavior was enough to close this issue.
