### ISSUE TITLE
Feature request: Force begin end inside if and match bodies

### ISSUE THREAD

**Issue by Pitometsu** [ocaml-ppx/ocamlformat#1085]
When wrap match case or then/else case, prefer begin/end instead of (/).

**Comment by gpetiot** [comment]
Sorry for the late answer, I think it's very unlikely for ocamlformat to automatically transform parentheses into begin/end, since this issue as been opened we have been preserving more and more begin/end keywords that are present in the original source (and missing cases should be fixed with time).
I am thus closing this issue.
