### ISSUE TITLE
Automatically wrap long strings

### ISSUE THREAD

**Issue by edwintorok** [ocaml-ppx/ocamlformat#11]
Taking an example from https://ocaml.org/learn/tutorials/guidelines.html

```ocaml
let universal_declaration =
  "-1- Programs are born and remain free and equal under the law;\n\
   distinctions can only be based on the common good."
```

gets converted to this and exceeds line length:
```ocaml
let universal_declaration =
  "-1- Programs are born and remain free and equal under the law;\ndistinctions can only be based on the common good."
```

An alternative is to use `{| |}` where newlines are preserved:
```ocaml
 {| -1- Programs are born and remain free and equal under the law;
distinctions can only be based on the common good.|}
```

**Comment by jberdine** [comment]
The current situation is indeed suboptimal. Continuation escapes are eagerly interpreted by the parser, so that by the time the formatter gets the parsetree, they have already been expanded.

It should be possible to implement a re-wrapping procedure to automatically insert line breaks with continuation escapes into long strings in order to stay within the margin.

**Comment by jberdine** [comment]
AFAIU this should be supported now by 56d48075752c8370b533a06550f1cbdfbe949deb. Please reopen with more info if not.
