### ISSUE TITLE
no-x options are not supported in .ocamlformat

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#1131]
Hi,

For boolean options, the following are supported in `.ocamlformat` files:

    OPTION=true
    OPTION=false
    OPTION

but `no-OPTION` is not supported (the 4 variants are available in the command line).

I think we should be consistent, so either support this, or disallow the short-form `OPTION` in config files. If anything, the error message can be improved:

    Fatal error: exception ("User Error: malformed .ocamlformat file"
      ("unknown option" no-OPTION))

Thanks

**Comment by Julow** [comment]
On the command line, only `--OPTION` and `--no-OPTION` are available (not `--OPTION=true|false`).

**Comment by emillon** [comment]
I stand corrected on this part.

**Comment by gpetiot** [comment]
I'm in favor of only improving the error message for now. Maybe we could also remove the `OPTION` as an accepted syntax of .ocamlformat files, if no big project uses it we can remove it without deprecating it first.
The more normalized the .ocamlformat files are, the better.

**Comment by gpetiot** [comment]
The first part was handled by #1869, and after thinking about the second part I think it's not necessarily a bad thing to keep supporting having `OPTION` in the configuration file instead of `OPTION=true` (e.g. for `disable` but not only).

Anyway since the mix-and-match of options will be deprecated in 0.21.0 this will become less of an issue, so I'm closing this one.
