### ISSUE TITLE
Bug: verbatim comment formatting not respected

### ISSUE THREAD

**Issue by ceastlund** [ocaml-ppx/ocamlformat#1132]
**Describe the bug**
If I format this code (with a formatted comment, taken from array.ml in Base)...
```
let _ =
  (* Optimal 5-element sorting network:

     {v
        1--o-----o-----o--------------1
           |     |     |
        2--o-----|--o--|-----o--o-----2
                 |  |  |     |  |
        3--------o--o--|--o--|--o-----3
                       |  |  |
        4-----o--------o--o--|-----o--4
              |              |     |
        5-----o--------------o-----o--5
      v} *)
  ()
;;
```
...ocamlformat reindents the formatted comment like this:
```
let _ =
  (* Optimal 5-element sorting network:

     {v
     1--o-----o-----o--------------1
     |     |     |
     2--o-----|--o--|-----o--o-----2
     |  |  |     |  |
     3--------o--o--|--o--|--o-----3
     |  |  |
     4-----o--------o--o--|-----o--4
     |              |     |
     5-----o--------------o-----o--5
     v} *)
  ()
;;
```

**How to Reproduce**
Run ocamlformat built from bcb803eb1867be97483ffe25e8ef0731a03bf19c with `--profile=janestreet`.

**Comment by gpetiot** [comment]
The `{v v}` do not have a special treatment in comments (only in docstrings). What is done with the comments (since the PR merged recently) is that each line of the comment is aligned (to the left) with the first line of the comment, so the number of spaces on the left (the indentation) is not preserved.

Unfortunately, there is not much that can be done, since if we try to preserve the indentation, the number of spaces increases with each iteration of the formatting since we can't know how many spaces Format decides to effectively indent (let's suppose you start at 2 spaces, so we preserve 2 spaces, but Format decides to indent of 2 spaces anyway, so in the next iteration we have 4 spaces to preserve, but Format still decides to indent 2 spaces, and now we have 6 spaces to preserve, and so on.)

A little trick to preserve these spaces would be to insert a character before these spaces like:
```ocaml
let _ =
  (* Optimal 5-element sorting network:

     . 1--o-----o-----o--------------1
     .    |     |     |
     . 2--o-----|--o--|-----o--o-----2
     .          |  |  |     |  |
     . 3--------o--o--|--o--|--o-----3
     .                |  |  |
     . 4-----o--------o--o--|-----o--4
     .       |              |     |
     . 5-----o--------------o-----o--5 *)
  ()
```

**Comment by jberdine** [comment]
Also note that 'banner comments' which start with a vertically-aligned column of `*`s are preserved verbatim.

Alternatively, maybe there could be some way to tell ocamlformat to parse a comment as if it was a docstring.

**Comment by ceastlund** [comment]
Would it be possible to have the janestreet profile format all (non-cinaps) comments as docstring comments? It's much more convenient to only learn one way of formatting comments, and to be able to move comments from ml to mli and back without having to reformat any parts that depend on alignment, etc. Also, it looks like ocp-indent respects `{v ...  v}` in all comments, so we would prefer to be consistent with that.

**Comment by Julow** [comment]
We could preserve whitespaces inside comments (eg. first detect the indentation then trim just that).
Formatting regular comments as docstrings makes sense but would need a bit of work before it can be enabled on a project (eg. preserving spaces and newlines)

**Comment by ceastlund** [comment]
I think preserving whitespace inside (non-cinaps, non-docstring) comments would be a good step for now.
