### ISSUE TITLE
Question: Should the documentation mention merge-fmt ?

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#1155]
and/or describe workflows to rebase changes across style changes

**Comment by emillon** [comment]
yes it should!

some workflows I'd like to see documented:

- how to rebase a branch across adoption of ocamlformat
- how to rebase a branch across an ocamlformat upgrade (if that's the same)
- how to reformat each commit in a branch (rather than at the end)

**Comment by jberdine** [comment]
Also, it would be good to basically repeat the merge-fmt documentation on how to set merge-fmt as a git merge tool and merge driver. It would probably also be a good idea to add some end-to-end tests to make sure that the right things happen when formatting fails in these situations. If we misreport error situations, it might be possible to delete code instead of signaling git that there is a problem.

**Comment by gpetiot** [comment]
I agree it would be better to promote `merge-fmt` and give some hints about how to use it, but I have some doubts about repeating the whole documentation here. I never had the chance to use it so far, but if anyone had more experience with it and has the time to modify the documentation he is very welcome :)

That would be a nice occasion to deprecate `ocamlformat-diff` (or simply remove it, since it has not been released on opam anyway) if it is superseded by `merge-fmt`.
