### ISSUE TITLE
Feature request: Sort Imports in Alphabetical Order

### ISSUE THREAD

**Issue by mukul-rathi** [ocaml-ppx/ocamlformat#1242]
I currently have a codebase where the imports are ordered as I need them, rather than in some systematic order, but this has led to a lack of consistency. 

It would be great if imports were automatically sorted in alphabetical order.

**Comment by Julow** [comment]
By imports you mean opens and aliases of modules that would be near the top of the file ?
```
open A
module B = Module_B
```

OCaml doesn't really have a concept of import. Using a module anywhere in the code is enough.

The problem I see is that the order of such declarations is important. (in my example, `Module_B` could be in scope only because of `open A`).
Even if we limit this feature to module aliases, OCamlformat doesn't have logic to analyze that.

**Comment by mukul-rathi** [comment]
Ah okay, thanks for the prompt reply!
