### ISSUE TITLE
Confusing interaction between options doc-comments and doc-comments-val

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#1338]
When we added `doc-comments-val` to control placement of comments around `val` items, `doc-comments`'s scope was reduced.
This made sense at the time because we planned to remove `doc-comments` but this have been reverted.

Given the name of the options, users will expect that `doc-comments-val` takes precedence over `doc-comments` but that its default doesn't matter. If `doc-comments-val` is not set, `doc-comments` should be used for `val` items too.

This could also be fixed simply by improving the documentation.

**Comment by samoht** [comment]
Having a priority between these options seems like a good idea. It will help reduce the confusion to our users, especially since these new options suddenly pop-ins the profiles and change their default behavior.

**Comment by CraigFe** [comment]
@samoht: I'm far from the most informed on this issue, but as I had some part in motivating the original change I'll try to give some context. (For the record, I find it difficult to see `doc-comments-val` as useful too :slightly_smiling_face:)

When the issue of consistent placement of doc comments was [first raised](https://github.com/ocaml-ppx/ocamlformat/issues/1010), I was thinking about doc-comments around `module` and `module type` definitions only, since these were previously placed according to a heuristic. It wasn't ideal to always place the comments after (since this is difficult to read for large `struct`s), so it was decided to co-opt the existing `doc-comments` option for this purpose, carrying over this decision to other types of structure item. 

In the [ensuing discussion](https://github.com/ocaml-ppx/ocamlformat/issues/1010), it seems that `doc-comments-val` was proposed as an orthogonal option for "_everything else_": types of structure items where many people will want the comments to go below (because Odoc renders the comments below).

I think this was confusing for two reasons:
1. the names `doc-comments` and `doc-comments-val` do not suggest orthogonality;
1. `doc-comments-val` did not include `type` declarations, for which many people want doc-comments to go below to match the Odoc rendering (I certainly just forgot about them at the time, which was a shame). I think this was the major cause of large undesirable diffs with `0.14.0`.

While changing `doc-comments-val` to be applied in priority order _does_ fix (1), I think the scope of `doc-comment-val` is incorrect: I can't really imagine why someone would want different `val` and `type` placement choices, and I don't think the choice of placement around `struct`s should be affecting `type`s.

Once again, I'm not particularly well-informed on this issue, but I suspect that the 'restricted scope' option shouldn't be applying to `val`s, but `module`s instead.

**Comment by Julow** [comment]
Types are not in the scope of `doc-coments-val` because it's not possible to place a documentation comments after variant declarations, except if the last constructor has a comment attached.
This, with the "module is simple" heuristic, were the reasons of our plans to place every before, for everyone.
That plan is cancelled, we'll try to fix that problem at an other level (for example, modifying OCaml's parser *or* deciding it's not a problem). `doc-comments-val` is a remnant for now, until at least the variant issue is fixed.
