### ISSUE TITLE
Feature request: Provide option to keep f x = fun a b ->

### ISSUE THREAD

**Issue by sheijk** [ocaml-ppx/ocamlformat#1373]
Currently expressions like this:
```
let make_compare op = fun lhs rhs -> ...
```
will always get rewritten like this
```
let make_compare op lhs rhs = ...
```
This makes code look more uniform but it loses information. Splitting a function declaration up in two like this can serve as documentation about the intended staging of the function. Thus losing this by formatting can decrease readability.

There are more [involved techniques](https://blog.janestreet.com/making-staging-explicit/) to make this explicit but they require refactoring and can be overkill for small projects or if a dependency to JaneStreet's libraries is not an option. 

An option to preserve this would be nice.

**Comment by jberdine** [comment]
Note that there is no distinction between those two styles in the parsetree data structure that ocamlformat works from. So preserving the distinction would require a hack to inspect the original concrete syntax with some heuristic to determine which style the original uses.

Using an explicit technique like Base.Staged makes the intent clearer to the reader, and since the [implementation](https://github.com/janestreet/base/blob/master/src/staged.ml) of is trivial, I would strongly advise to just use that, reimplementing it in a few lines if you can't take a dependency on base.

**Comment by CraigFe** [comment]
I have occasionally added type annotations to such functions for this reason:

```ocaml
(* Annotation prevents the [fun] from being collapsed *)
let make_compare (type a) op : a -> a -> int =
    fun lhs rhs -> ...
```

My experience is that the code generally reads better with such annotations and so I personally don't mind needing a workaround.

I certainly can't imagine myself using `Base.Staged` for such a case, since I see that as mostly a tool for the _consumer_ of the API to be wary of side effects of partial application. I think there are valid reasons to internally document _intent_ without needing to tie the API down to that intent.

<hr/>

As a non-maintainer, I have two thoughts on the feature request itself:

- I much prefer collapsing `= fun a ->` to `a =`, forcing me to confront that they're identical (especially when dealing with beginners / students). Such cases often come up in refactoring, and I'm glad that OCamlformat gets rid of them automatically for me.

- This case is symmetric with the `module A (_ : T) =` /  `module A = functor (_ : T) ->` one, and I would expect OCamlformat to be consistent in its choice.

The goals of "uniformity" and "allowance for demonstrating intent" seem exactly at odds to me, and I think OCamlformat should be consistent one way or another (or provide a _high-level_ option / profile for picking between the two). Personally, I definitely prefer the former.

**Comment by gpetiot** [comment]
I tend to prefer being symmetric with the `module`/`functor` formatting.

I'm not sure when it can be beneficial to collapse `= fun a ->` to `a =` as the latter is shorter and you're more likely to write it naturally. I think if you write the former it's deliberate and it carries some meaning (more meaning than adding some space here or there).

btw feel free to try #1380 in case there are some cases that I missed.

**Comment by CraigFe** [comment]
> I'm not sure when it can be beneficial to collapse `= fun a ->` to `a =` as the latter is shorter and you're more likely to write it naturally. I think if you write the former it's deliberate and it carries some meaning (more meaning than adding some space here or there).

This happens reasonably often to me when I delete an intermediate line.

```diff
 let foo =
-  let ref counter = 0 in
   fun () ->
```

and in these cases I appreciate OCamlformat making my code uniform. I suspect that many (most?) occurrences will not be deliberate for this reason.

**Comment by gpetiot** [comment]
Given the discussion in #1380 it will probably not be implemented, the alternatives suggested by Josh and Craig are indeed sufficient.

**Comment by jberdine** [comment]
Closing as there aren't currently plans for this. As long as the implementation would require referring back to the concrete syntax, this isn't a good functionality vs implementation complexity trade-off. We can reopen if new info comes up, the parsetree changes, etc.
