### ISSUE TITLE
Bug: ocamlformat tells me to report this bug

### ISSUE THREAD

**Issue by dinosaure** [ocaml-ppx/ocamlformat#1388]
I did not go further but it seems that we got a bug about documentation which can be easily reproducible when the CI got it too:

https://ci.ocamllabs.io/github/mirage/ocaml-conduit/commit/c8bbe6f6b7138da2c1dd2bbb015d09d872e8301a/variant/(lint-fmt)

The commit is: https://github.com/mirage/ocaml-conduit/pull/311/commits/c8bbe6f6b7138da2c1dd2bbb015d09d872e8301a

So if you clone at this commit and do a simple `dune build @fmt`, you should reproduce the problem. On our side, we added `parse-doctstrings=false` into the `.ocamlformat` file.

**Comment by jberdine** [comment]
This is due to the docstring not parsing because of a `]` instead of a `}` [here](https://github.com/mirage/ocaml-conduit/blob/c8bbe6f6b7138da2c1dd2bbb015d09d872e8301a/lwt/conduit_lwt.mli#L29). If you change that typo it seems to work for me.

I wonder if there is something better we can do regarding the error message in the case that a docstring does not parse. @gpetiot, any ideas?

**Comment by gpetiot** [comment]
As Josh said this isn't a bug but badly written error messages, I've improved the situation in #1654, that should be enough to detect what should be changed in the doc-comment. I'm closing this issue but feel free to re-open if necessary!
