### ISSUE TITLE
Inconsistency of type constrained functions

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#1394]
There is a small inconsistency between the formatting of type constrained anonymous functions and named functions:

```ocaml
let _ = fun x : t -> y
let _ = fun x -> (y : t)
let f x : t = y
let f x = (y : t)
```

get formatted as:
```ocaml
let _ = fun x : t -> y
let _ = fun x : t -> y
let f x : t = y
let f x = (y : t)
```

The type constraint gets moved at the beginning for anonymous functions but not for named functions. Should we change that? (the named case I mean) @jberdine @Julow @emillon

**Comment by Julow** [comment]
The annotation moved from the right (always) to the left (always) recently in https://github.com/ocaml-ppx/ocamlformat/pull/1381
The `let` case was implemented in https://github.com/ocaml-ppx/ocamlformat/pull/815

Keeping the original syntax is important for first-class modules (https://github.com/ocaml-ppx/ocamlformat/issues/629).

**Comment by gpetiot** [comment]
I don't think the `fun` case should be changed.
But what about always moving the type annotation from right to left for `let` as well?

I don't think it would be an issue to reformat `let x = (module struct end : S)` as `let x : (module S) = (module struct end)` but it would be consistent with the first case.

**Comment by Julow** [comment]
The annotation on module packs is often mandatory (to type-check) and are part of the syntax, eg. it's not `((module struct end) : (module S))`.
I think this would be annoying when refactoring code:
```
f (module M : S)
```

to
```
let x : (module S) = (module M) in
f x
```

**Comment by ceastlund** [comment]
I'm a little confused with some of the examples above because they don't seem consistent with the proposal. The proposal is about the shorthand `let f x = (y : t)` for `let f = fun x -> (y : t)`, and whether to rewrite it as `let f x : t = y`, but a lot of the examples don't contain a `let f x =` at all.

There's no proposal to add a `let x` where one doesn't exist, nor to rewrite `let x = (y : t)` in the absence of a function definition, is there?

**Comment by jberdine** [comment]
To my view it would be more uniform to format
```
let _ = fun x : t -> y
let _ = fun x -> (y : t)
let f x : t = y
let f x = (y : t)
```
to
```
let _ = fun x : t -> y
let _ = fun x : t -> y
let f x : t = y
let f x : t = y
```
In both cases the rule is to place type ascriptions on the result of a function after the parameters.

The case of first-class modules could be handled as a special case because it simply is a special snowflake in the language.

For cases like formatting `let x = (y : t)` to `let x : t = y`, I can see the motivation but think that doing that would be working toward a more wide-scoped rule along the lines of "place type ascriptions as high in the parsetree as possible". I do not think that doing this is a prerequisite for the treatment of functions above.

**Comment by gpetiot** [comment]
There is a first draft in #1397
