### ISSUE TITLE
`[...]` vs `{[...]}`: missing odoc functionality?

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#1735]
I'm trying to handle the difference between `[...]` and `{[...]}` docstring elements more correctly, and it seems that perhaps we need the odoc parser to preserve more of the info that is in the source.

Ideally, the content of `[...]` should be formatted, while `{[...]}` is expected to be preformatted and so should be left untouched. I am not finding a distinction between these two cases in the parsed form, am I missing something?

Cc: @Julow @jonludlam

**Comment by Julow** [comment]
`[ ... ]` is an "inline" element and is expected to contain a small amount of text (eg. an identifier or a function call), I'm not sure it's worth trying to format it.
`{[ ... ]}` is a "block" element and is expected to contain a multi-line piece of OCaml code and is currently formatted by OCamlformat. (falls back to the initial text if parsing fails)

Since recently, there's a way to attach metadata to code blocks:
```ocaml
(** {@ocaml[
    ...
    ]} *)
```

The first word is the language used within the block. We could disable formatting of code blocks with a language that is not "ocaml". (currently, not looking at the language tag)
Also, there's the `{v ... v}` block for preformatted text, that OCamlformat preserves.
