### ISSUE TITLE
Bug: trailing carriage returns removed from string literals

### ISSUE THREAD

**Issue by bcc32** [ocaml-ppx/ocamlformat#1748]
**Describe the bug**
ocamlformat removes trailing carriage returns from delimited string literals.  I think this might be related to the recent change to CRLF-handling behavior, but it seems like ocamlformat should never touch string literals in a way that would change the actual contents of the string.

**How to Reproduce**

Below is an example file.  Please replace `^M` with actual carriage return characters.

```ocaml
let%expect_test _ =
  do_test (fun () ->
    let%bind () = system "cat foo.csv" in
    [%expect
      {|
    e,d,f^M
    "x
    x",x,xxx^M
    e,d,f
    "x
    x",x,xxx^M
    yy,y,"y
    yy"
   |}];
    return ())
;;
```

When ocamlformat is run on the above file, the carriage returns disappera.

Options:
```
--profile=janestreet
--enable-outside-detected-project
```

**Comment by bcc32** [comment]
FYI, this bug was observed at a572aee651f859a8ca600c59e76c4d34db6954c8.

**Comment by nojb** [comment]
> ocamlformat removes trailing carriage returns from delimited string literals. I think this might be related to the recent change to CRLF-handling behavior, but it seems like ocamlformat should never touch string literals in a way that would change the actual contents of the string.

Thanks for the bug report! Indeed we were aware that the changes to the handling of line endings could cause a problem like the one you encountered (see discussion in #1703). My view is that embedding control characters in string literals is inherently fragile, and that explicitly escaping the CRLF is an acceptable workaround when the difference between CRLF and LF is crucial.

> it seems like ocamlformat should never touch string literals in a way that would change the actual contents of the string.

The problem is that without knowing the intent of the code it is hard to say if this is the right thing to do or not. If you edit your file on a Windows editor you may be inserting CRLF instead of LF "by accident" and normalizing the newline in that case is the right thing to do. Leaving the content of literal strings untouched means that `ocamlformat` may be producing mixed-encoding files routinely even when not needed.

In the end, I went for the simplest possible semantics of the new option, which is to normalize newlines across the board. In #1703 it was suggested that `ocamformat` should output a warning when rewriting string literals with embedded newlines to warn the user of this problem. This looks like a good mitigation to me. Would you be happy with such a warning?

**Comment by ceastlund** [comment]
Could we have an option to control this behavior, and have it set in the janestreet profile to never rewrite string contents? We recognize the current behavior may be right for some users, but it's not right for us. A warning doesn't really help because our files with CRLFs would still not be styled faithfully. Specifically, we have expect tests based on output from windows programs, and if the tests don't include the CRLFs they fail.

**Comment by nojb** [comment]
> Could we have an option to control this behavior, and have it set in the janestreet profile to never rewrite string contents? We recognize the current behavior may be right for some users, but it's not right for us. A warning doesn't really help because our files with CRLFs would still not be styled faithfully. Specifically, we have expect tests based on output from windows programs, and if the tests don't include the CRLFs they fail.

We could introduce an option `line-endings: lf-unnormalized` which does no normalization at all after `ocamlformat` runs and opens the output channel in binary. This is equivalent to the "old" behaviour if you are working on Unix (on Windows, the newlines inserted by the pretty printing algorithm would be LF). Would that be enough? @hhugo what do you think?

Not rewriting the newlines of *just* string literals would complicate the implementation considerably and I would rather not do that if we can help it.

**Comment by ceastlund** [comment]
I think going back to the old behavior would be fine for us, so that option would be great if you can add it, thanks.

**Comment by nojb** [comment]
> I think going back to the old behavior would be fine for us, so that option would be great if you can add it, thanks.

It would be the old behaviour only on Unix; on Windows the newlines from the pretty printing algorithm would be LF instead of CRLF as they used to be.

**Comment by ceastlund** [comment]
Sounds fine, that works for us.

**Comment by hhugo** [comment]
> Not rewriting the newlines of _just_ string literals would complicate the implementation considerably and I would rather not do that if we can help it.

It would complicate things a bit but I think I would prefer that solution because we don't need to introduce a new warning when modifying AST and we don't need a new option to satisfy janestreet.

About the implementation, I would collect locations with an AST mapper and update the normalization loop  to skip over theses locations. I'm expecting between 10 and 20 extra lines of code

**Comment by nojb** [comment]
> > Not rewriting the newlines of _just_ string literals would complicate the implementation considerably and I would rather not do that if we can help it.
> 
> It would complicate things a bit but I think I would prefer that solution because we don't need to introduce a new warning when modifying AST and we don't need a new option to satisfy janestreet.
> 
> About the implementation, I would collect locations with an AST mapper and update the normalization loop to skip over theses locations. I'm expecting between 10 and 20 extra lines of code

Fair enough, implementation as per your suggestion at #1754; review appreciated!
