### ISSUE TITLE
Deprecating option 'sequence-blank-line'

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#1826]
I would like to advocate for the deprecation of the option `sequence-blank-line` for next release ocamlformat 0.20.0, before removing it by version 1.0. The default behavior would then be the same as the current `sequence-blank-line = compact`.

The behavior `sequence-blank-line = preserve-one` would then disappear, there will then be a change for the `conventional` profile.

The arguments are:
- this feature adds some maintenance difficulty to ocamlformat (with some bugs like #1796)
- preserving blank lines between this kind of items is not really the goal of an autoformatter
- ocamlformat has way too many options, and it is against our goal of having a uniform/standard formatting style
- having no blank line between local let-bindings and in-sequence expressions was the original choice of ocamlformat, and is still the default behavior for the `ocamlformat` and `janestreet` profiles
- most people use the current `compact` behavior from what we have gathered from our surveys

cc @Julow @jberdine @hhugo @samoht @avsm @CraigFe @tmattio

**Comment by CraigFe** [comment]
As a user, I'm somewhat attached to the `preserve-one` behaviour, as I use it regularly. I find it's particularly helpful for grouping assertions in tests, for example:

```ocaml
for i = 0 to 1_000_000 do
  (* Add a new element: *)
  let new_elt = random_string () in
  String_set.add set new_elt ;
  Stdlib.Hashtbl.add reference_tbl new_elt () ;
  Vector.push reference_vector new_elt ;

  (* Pick a random existing element and check [mem] is true: *)
  let elt = Vector.get reference_vector (Random.int (i + 1)) in
  assert (Stdlib.Hashtbl.mem reference_tbl elt) ;
  String_set.mem set elt |> check_bool __POS__ ~expected:true ;

  (* Pick a random non-existing element and check [mem] is false: *)
  let non_elt = random_string () in
  assert (not (Stdlib.Hashtbl.mem reference_tbl non_elt)) ;
  String_set.mem set non_elt |> check_bool __POS__ ~expected:false
done
```

(Taken from [this PR](https://gitlab.com/tezos/tezos/-/merge_requests/3526/diffs), written today, which uses quite a lot of such blank lines.) There's some similar usage of grouped assertions in the Dune test suite (e.g. [here](https://github.com/ocaml/dune/blob/main/test/expect-tests/fiber/fiber_tests.ml#L54-L65)). The trade-off is naturally that some such blank lines will be unintentional, and it's potentially surprising that they don't go away – I've seen at least one discussion with a developer who was surprised about this behaviour.

Looking over the Irmin codebase, I think the vast majority (all?) of such blank lines were put there intentionally, and I don't find it taxing to `dd` any unintentional ones that do happen during editing. Indeed, the oldest sections of the Irmin test suite _without_ such blank lines tend to be the hardest to read (usually because there were initially blank lines for grouping, but they got wiped when OCamlformat was adopted).

I agree that preserving the blank line is against OCamlformat's general policy of retaining only information in the AST, modulo comments and other syntactic weirdnesses (extension point sugar and `Array.get` / `String.get` come to mind), but on balance I think `preserve-one` is a good deviation from that policy. The alternative is having to re-structure my code to coerce the formatter into allowing grouping of bindings / sequences; this is the formatter adding to mental load rather than taking it away.

FWIW, I don't agree with @Julow's comment [here](https://github.com/ocaml-ppx/ocamlformat/issues/1796) that preserving space _before_ the `in` should be valid: for me this crosses the line from "_allowing the user to visually group sequences_" to just "_allowing the user to format their code how they like_".

Above all, it's definitely worth reducing the maintenance burden of `ocamlformat`, and removing `preserve-one` seems worthwhile for that reason alone. (And as a non-maintainer I'm obviously a poor judge of that :upside_down_face:.) My case is that – all other things being equal – I'd rather have `preserve-one` than not.

> most people use the current compact behavior from what we have gathered from our surveys

I'm surprised by this, given that `preserve-one` is the current default. Are most projects not using the `conventional` profile?

**Comment by jberdine** [comment]
At fb we have a lot of code that uses `sequence-blank-line = preserve-one`, e.g.: [hack](https://github.com/facebook/hhvm/blob/master/hphp/hack/.ocamlformat), [flow](https://github.com/facebook/flow/blob/main/.ocamlformat), [pyre](https://github.com/facebook/pyre-check/blob/8c4fb603e41dbc80afb198401501bbe4f360be8b/source/.ocamlformat).

More, it is a feature that those projects waited for before they were willing to use ocamlformat.

I understand the undesirability of the implementation of the "preserve" options, but I would be cautious here.

**Comment by gpetiot** [comment]
I didn't have a detailed look at every use in those projects but from what I got from `flow` is that most usecases are:
```ocaml
let x = y in

(* having a blank line before a comment *)
something
```

```ocaml
something ;

(* blank line before this comment *)
something
```

It would be far easier to maintain this behavior, make sure there is a blank line before a comment in a list of let bindings or in a sequence of expressions (whether it was in the source or not), and not preserving blank lines in other cases, as I feel the other cases won't be missed as much?

**Comment by CraigFe** [comment]
For my part, preserving this behaviour only with a leading comment would be a good compromise. Great to hear that it would be easier to maintain this way.

**Comment by jberdine** [comment]
@gpetiot, I'm not sure I understand your proposal. Do you mean to always have an open line before a comment in a sequence, or to preserve open lines already in the input only if they come immediately before a comment?

**Comment by gpetiot** [comment]
I had in mind the first case so we wouldn't have to lookup in the source whether there is a blank line or not. The idea is that separating the comment from the code before helps to make the code easier to read in my opinion, and I noticed that these were the cases were there were blank lines in `infer`.

(I'm trying to find a solution that matches:
- not looking up the concrete input if possible
- preserving some line blanks since this is a deal breaker for the fb projects you listed
- reducing the number of behaviors to maintain)

**Comment by jberdine** [comment]
Thanks for clarifying. This isn't an issue for infer, which doesn't set `sequence-blank-line`, but I will do some investigation with the other projects.

**Comment by jberdine** [comment]
I'm not sure if users of `sequence-blank-line = preserve-one` will be happy to have an open line before every comment in a sequence, but just to note first that such behavior cannot be the only option: it is necessary for the current behavior `sequence-blank-line = compact` to remain possible.

Separately, are there particular difficulties with this option in terms of ongoing maintenance that you can describe to me? Maybe it is just a matter of generally wanting fewer configuration options. But looking at the implementation and git log, this one does not jump out at me as being a problem, but maybe I'm overlooking things.

**Comment by gpetiot** [comment]
Besides the bug you reported in #1835, another pain point is relying on the tokens of the concrete input (Source.empty_line_between -> Source.tokens_between), since we also wanted to reduce our dependency to concrete input (there must be an issue open somewhere about that).

But maybe this option is not a primary candidate for deprecation _yet_, we can start with the less controversial ones first.

**Comment by jberdine** [comment]
I think https://github.com/ocaml-ppx/ocamlformat/issues/1835 is in a different category: something to fix upstream rather than an ongoing complication for us. Also, if those locations are off, then it seems likely that they cause odd comment placement in some corner case too, so better to fix irrespective of `sequence-blank-line`.

**Comment by jberdine** [comment]
For not depending on concrete input, I think that it would be more effective to gather together an overall picture of everything that relies on it, and consider it all together. If the main benefit is to remove reliance on the concrete input, then it makes sense to be clear about how far things need to go before the benefit is realized. Currently the only form of backtracking we have for formatting is to format, check the concrete input on the next iteration, and then format again. Taking that away without replacing it with some form of backtracking is going to be a significant change in the output, that I don't expect any users to be happy about. So I think an overall plan is needed for how to implement backtracking in a preferable way, rather than to try to remove some uses of it without being confident that the benefit of removing them all can be achieved. Perhaps one relatively small implementation change to make things more robust would be to do the first iteration of formatting without using e.g. `Location.is_single_line` but then using it in later iterations.

**Comment by gpetiot** [comment]
For now this option's behavior will be preserved in each preset profile, I'm thus closing this issue.
