### ISSUE TITLE
Discussion: Policy for deprecation of options/

### ISSUE THREAD

**Issue by psafont** [ocaml-ppx/ocamlformat#1923]
The xapi project has been affected by changing formatting options twice already, and at his point is making backports to LTS versions more difficult than it should as this change compounds with internal changes and requirements.

I'm trying to see what the best plan of transition to a point where ocamlformat gives the project a stable format.

I've noticed that the current [plan](https://github.com/ocaml-ppx/ocamlformat/wiki/OCamlFormat-roadmap#reduce-the-number-of-possible-configurations) includes the removal for _all_ the options used currently in all the project's repositories: 
```
profile=ocamlformat
indicate-multiline-delimiters=closing-on-separate-line
if-then-else=fit-or-vertical
dock-collection-brackets=true
break-struct=natural
break-separators=before
break-infix=fit-or-vertical
break-infix-before-func=false
sequence-blank-line=preserve-one
```

Some of the options like `sequence-blank-line` have more than 50 usages in the survey, are they still going to be removed? They don't seem to be the default in the profile used, and still widely used for a total of 250 projects

Is the fastest option to get to a stable format to remove all the options at once? When I did the testing to see which profile was closes ocamlformat with option was a good, maybe there's a profile that tries to minimize lines when adding elements to collections a possibility? (it's the biggest change I can see when removing all the options)

**Comment by gpetiot** [comment]
What is planned (for now) is to not be able to explicitly set these options, but they will still be used as part of the preset profiles. To follow up the example of the `sequence-blank-line` options:
- default profile: `sequence-blank-line = preserve-one` will still be applied
- ocamlformat profile: `sequence-blank-line = compact` will still be applied
- janestreet profile: `sequence-blank-line = compact` will still be applied
- it won't be allowed to set this option outside of the existing profiles

**Comment by edwintorok** [comment]
I think some of the changes we made to ocamlformat defaults were to:
* reduce merge conflicts, e.g. adding a new element to a long list should try to avoid generating merge conflicts (if 2 different PRs add new elements) by not having the closing brace on the same line as the list elements. And even if they generate a merge conflict it is easier to solve a merge conflict that purely adds 2 lines, vs one that also moves the closing brace around.
* reduce wide changes between our LTS branch that got formatted with an older version of ocamlformat, where a new version of ocamlformat has changed defaults. (unless there is a good reason to change it we'd probably prefer to keep the formatting as it was in the older version)
 
I can understand the need to reduce the proliferation of settings, but in that case it would be nice if:
* there was a profile focused on making interaction with `git` nicer: formatting choices that reduce the chance of conflicts, such as keeping list elements on their own lines and not making the closing brace part of the list element, to allow easily appending new elements to the end of the list (would be nice to have this for `dune` too. We use our own s-expression pretty printer there to get a one-library/line kind of formatting there: https://github.com/lindig/jbuild-pp. The defaults cause too many merge conflicts every time the dependencies are updated)
* there was be a way to stay compatible with the previous version of ocamlformat for a while. One might want to upgrade ocamlformat (e.g. to get a bugfix, or because the rest of the ecosystem imposes it via constraints - i.e. keeping old ocamlformat version prevents upgrade of other libraries), but without doing a massive reformat of the codebase. This might be solved by making the 3 profiles mentioned above versioned, and when the defaults change between ocamlformat introduce a new version

I've been pointed to a `merge-fmt` tool that might alleviate some of these concerns, but haven't tried it out on actual LTS backport on our codebase yet.

Would be good to get some feedback from other projects that maintain multiple release branches: surely we aren't the only ones who maintain multiple LTS versions of their projects and need to backport bugfixes?

**Comment by gpetiot** [comment]
I understand your concern, out of curiosity how does the `profile = sparse` look on your code, it has been made to vertically expand the code to minimize the diff, so it should be git-friendly. It is currently deprecated on the main branch but we can choose to un-deprecate if it makes sense.

As to having the bugfixes without having formatting changes I don't know how to have that without maintaining an unhealthy amount of branches (keep in mind that it is already difficult to maintain ocamlformat with just one branch (especially on my own), just like any project).
Ocamlformat is still unstable (not yet in version 1.x.y) so there is a bit of back and forth with options here and there but we are slowly converging.
We made the choice for quite some time/releases now that (_I quote from the README_) it's better to see ocamlformat as a tool to apply *a* style, rather than a tweakable tool to enforce any existing style.

Having a diff for each ocamlformat upgrade is still difficult to avoid until we stabilize enough, but there are ways to ease this experience, e.g. make the reformatting commits invisible when using git blame: https://github.com/ocaml-ppx/ocamlformat#using-ocamlformat-without-breaking-git-blame

**Comment by psafont** [comment]
I've set up a branch with the reformatting using sparse: https://github.com/psafont/xen-api/tree/sparse

Using the sparse profile from ocamlformat 0.18 gives this changeset:
`707 files changed, 70197 insertions(+), 50361 deletions(-)`
There are some changes that benefit git diffs, other don't seem to bring any particular upside:
- Adding empty lines
-  first item in the list is in the same line as the opening square bracket
- Moving the then to another line, losing the indentation difference from the if is also that affects readability 

Upgrading to 0.19 and reformating gives us:
`27 files changed, 81 insertions(+), 97 deletions(-)`
While I prefer the formatting of the newer version, it adds churn, which we'd like to avoid


Maintaining ocamlformat, but without options changes fewer lines:
`634 files changed, 18506 insertions(+), 37391 deletions(-)`
and the update to 0.19:
`27 files changed, 81 insertions(+), 112 deletions(-)`

Do you anticipate the changes in format to subside now that the work has converged to remove options and stabilization? (I guess to prepare for 1.0)

**Comment by gpetiot** [comment]
Yes I predict the changes induced by each future upgrade will be less and less as we remove options and as we remove the ability to mix and match options outside of profiles. It will be easier for us to test every possible configuration and to catch bugs this way.
We want to improve the quality on the few styles we will maintain, and that's something that is hard to see as a user so you have to trust me on this, but having too many options was clearly getting in the way of the maintainance of ocamlformat, high cost for few benefits: too few users for some options, but that was preventing us from fixing bugs/inconsistencies impacting more users.

**Comment by psafont** [comment]
I think we'll wait to update ocamlformat until the format has been stabilized and bugs in it have been stamped out. I'd rather have one big jump in a single update rather than progressively.

Thanks for your time!
