### ISSUE TITLE
Regression with "local open"?

### ISSUE THREAD

**Issue by smondet** [ocaml-ppx/ocamlformat#196]
I just upgraded my opam-pin to `master`, and noticed this diff:

```patch
-      $ Arg.(
-          let doc = "Output all." in
-          value & flag & info ["all"] ~doc)
-      $ Arg.(
-          let doc = "Commit to git." in
-          value & flag & info ["commit"; "c"] ~doc)
+      $ (let open Arg in
+        let doc = "Output all." in
+        value & flag & info ["all"] ~doc)
+      $ (let open Arg in
+        let doc = "Commit to git." in
+        value & flag & info ["commit"; "c"] ~doc)
       $
```

The previous version with the parentheses is definitely better, right?

(and also the indentation of `let doc ` is weird; it doesn't match the `let open`)

**Comment by smondet** [comment]
Also, there are `Some_module.[a; b; c]` transformed into `Some_module.([a; b; c])`, adding useless extra parens.

**Comment by hhugo** [comment]
This is due to https://github.com/ocaml-ppx/ocamlformat/pull/149. The behaviour is expected.
I'm not able to reproduce the behaviour described in your second comment.

**Comment by jberdine** [comment]
There is a bit of a conflict here between two special cases that force formatting rather than relying on the margin:

1. `let open` expressions are forced into the short form when they are arguments of applications;
2. `let open` (and other) expressions are forced to break across lines when they have a `let` subexpression.

In the example, the special case 1. gets overridden by 2. My understanding is that the motivation for 2 is primarily to break the lines, and the change from short to long form of `let open` is a side effect. It is not obvious what is best here. I wonder if `let open` expressions should use the short form if they need to be parenthesized anyhow. What do others think? @hhugo I notice that there aren't any cases in the tests for #149 where a `let open` expression is parenthesized, so it's not obvious what the intent there was in this case.

**Comment by jberdine** [comment]
@smondet, does the `let-open` option from #267 resolve this for you?

**Comment by smondet** [comment]
@jberdine yes and I think `preserve` is indeed a good default.

I was testing with this, I don't know why there is an extra new-line after the 3rd (and last) `$` but I don't think it's a problem:

```ocaml
    $ Arg.(value & flag & info ["test"] ~doc:"Also run some tests")
    $ Arg.(
        let doc = "Temporary build path." in
        required & pos 0 (some string) None & info [] ~doc)
    $
    Arg.(
      let doc = "Output tar.gz path." in
      required & pos 1 (some string) None & info [] ~doc) )
```
