### ISSUE TITLE
Strange indentation of long `if ... then ... else ...` within expression (master)

### ISSUE THREAD

**Issue by smondet** [ocaml-ppx/ocamlformat#197]
With `ocamlformat` pinned to `master` we get the "then-expression" at the same level as the `if` and the `else` keyword at the level of the parenthesis:

```ocaml
let x =
  [ 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42
  ; ( if true || true || (true && false) then
      42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42
    else
      41 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42 + 42
      + 42 + 42 + 42 ) ]
```

**Comment by jberdine** [comment]
This looks as expected to me, but I'm not impartial...

The aim here is to have the `then` and `else` expressions indented to the same level without consuming more space than needed to show the structure. Indenting the whole expression from the left of the `(` instead of the left of the `if` is analogous to the treatment of parenthesized infix applications.

Do you prefer the output with `--if-then-else=keyword-first`?

**Comment by jberdine** [comment]
@smondet, does `if-then-else=keyword-first` resolve this for you?

**Comment by smondet** [comment]
It indeed makes it more readable, it'd be great if `--if-then-else=keyword-first` was the default :)

**Comment by jberdine** [comment]
Ok, I'll close this then. The question of defaults is much broader and we need to think about changing them in as consistent a way as possible (e.g. at least default options are basically "compact" or are basically "sparse", not a mix of both).
