### ISSUE TITLE
Assumptions on non-doc comments?

### ISSUE THREAD

**Issue by smondet** [ocaml-ppx/ocamlformat#198]
This:

```ocaml
let x = 42 (* comment on 42 *)
let x = 43 (* comment on 43 *)
let z = 44
```

gets transformed to this:

```ocaml
let x = 42

(* comment on 42 *)
let x = 43

(* comment on 43 *)
let z = 44
```

is it the expected behavior?

**Comment by jberdine** [comment]
Attachment of (non-docstring) comments is fragile / tricky. This behavior is, I think, suboptimal, but is "expected" given the [heuristic](https://github.com/ocaml-ppx/ocamlformat/blob/master/src/Cmts.ml#L321) that chooses whether to attach a comment to the parsetree node before or after it. That function could definitely be changed, but it has very significant effects since it is also tricky to keep comments from disrupting the line breaking and indentation of surrounding code too badly. Also note that whatever information the heuristic uses should be guaranteed to be preserved by the formatter, otherwise it is very easy to get cases where each iteration of formatting moves the comments, often cycling between a small number of configurations, never stabilizing. I spent a while considering alternative heuristics, but it could use more attention and iteration on a large body of code.

**Comment by jberdine** [comment]
Another idea related to this would be to prefer to attach a comment to the phrase before if the preceding token is not a keyword when the token following the comment is a keyword, and vice versa. I don't know how well to expect this to work in general, but perhaps it's worth trying.

**Comment by gpetiot** [comment]
On master this is formatted as:
```ocaml
let x = 42 (* comment on 42 *)

let x = 43 (* comment on 43 *)

let z = 44
```
so we can close this issue.
