### ISSUE TITLE
De-deprecate align-* features

### ISSUE THREAD

**Issue by giltho** [ocaml-ppx/ocamlformat#1996]
Hello :)

The last `.ocamlformat` upgrade incurred [massive diffs](https://github.com/GillianPlatform/Gillian/pull/92/files) on my project, and I did enjoy the features.

I couldn't find a related announcement, but I did search through the issues and understood that it was mostly a maintainability burden issue.

I just want to emphasize that I __do__ definitely understand that point, and I am not *demanding* anything. I discussed the subject, and [was pointed out](https://twitter.com/vphantom/status/1487131328395026436) that maybe it was due to the fact that maintainers of ocamlformat did not know how widely the features were used. Showing that people are actually using these features is the goal of this issue.

If you still believe that the maintenance burden is not worth it, do close this issue. I am, in any case, extremely grateful of the work done here!

**Comment by gpetiot** [comment]
Hi, here is a detailed answer about why the deprecations: #1997 

About the `align-*` options in particular I have pinged one of the biggest projects using them https://github.com/owlbarn/owl/issues/586. Out of curiosity where would be the most convenient place for you to have this kind of discussion in the future? ocaml.discuss.org, the ocaml discord server, the ocamllabs slack, other?

The main reason (the other reasons are listed in #1997) we deprecated these options is because they are really not diff-friendly:
For the sake of the argument let's consider part of your code:
```ocaml
let to_string = function
  | Mint8signed    -> "int8signed"
  | Mint8unsigned  -> "int8unsigned"
  | Mint16signed   -> "int16signed"
  | Mint16unsigned -> "int16unsigned"
```
If you add a line longer than the longest one, if you use this option you would get:
```diff
let to_string = function
-  | Mint8signed    -> "int8signed"
-  | Mint8unsigned  -> "int8unsigned"
-  | Mint16signed   -> "int16signed"
-  | Mint16unsigned -> "int16unsigned"
+  | Mint8signed      -> "int8signed"
+  | Mint8unsigned    -> "int8unsigned"
+  | Mint16signed     -> "int16signed"
+  | Mint16unsigned   -> "int16unsigned"
+  | Mint16unsignedxx -> "int16unsignedxx"
```
the same argument can be made if you remove the longest line. This is of course expected but this adds a lot of noise to the diff when reformatting and this is something we try to avoid with ocamlformat.

Finally I think this kind of feature does not have a place in a code formatter that treats the AST, and it could be achieved as a post-processing step of the code (in a separate tool), something like a grep-sed or something else (maybe something similar to what ocp-indent does for the indentation). In ocamlformat this is implemented by formatting a first time the part that will determine the length of the alignment padding (e.g. the pattern on the left of the arrow) to first determine the longest length, then reformatting everything, which is not efficient (multiple re-formatting rounds), that's why I think a post-processing step would be more appropriate (it would already know which line is the longer).

**Comment by giltho** [comment]
Thank you very much for taking the time to provide such a detailed answer. 

I believe such discussions are good to have on discuss.ocaml.org, as it is openly accessible to read without a discord account or a slack invitation. 

Yes, I always was a bit sad about the fact that adding a variant could change the whole block, but did accept it as a necessary evil for a slightly more beautiful code.

The argument of making it a separate post-processing tool is actually good. For something like that, the best scenario would be to be able to specify "post-processing" features in the `.ocamlformat` that would be detected by ocamlformat itself, which would then be in charge of calling the tools. 

For example, one have the following ocaml format `.ocamlformat` file
```
# normal ocamlformat options

<plugin: ocaml-align/version: 1.0.0>
option1=value1

<plugin: other-plugin/version: 2.1.0>
...=...
```
And then ocamlformat would simply call the program `ocaml-align` with the given options
Granted that would make the parsing of `.ocamlformat` files slightly more complicated, but it would be good since it would not modify the behaviour of `dune build @fmt` at all. It would also keep `.ocamlformat` as the sole file for deciding on code formatting, and ocamlformat would bake sure the the plugins are always called in the same order, so that the behaviour is consistent

That being said, I'm throwing ideas and know I will not have time to implement them...

Anyway, thank you for your answer, I'll close this issue!

**Comment by roddyyaga** [comment]
> The main reason (the other reasons are listed in #1997) we deprecated these options is because they are really not diff-friendly: For the sake of the argument let's consider part of your code:

I would argue this is only true if you have a deficient diff tool. E.g. [patdiff](https://github.com/janestreet/patdiff) will collapse whitespace-only changes by default, and GitHub [can do that too](https://github.blog/2018-05-01-ignore-white-space-in-code-review/) (although it seems like you have to enable it for each pull request).
