### ISSUE TITLE
Does not output to stdout by default

### ISSUE THREAD

**Issue by hcarty** [ocaml-ppx/ocamlformat#2]
The `--help` text indicates that `ocamlformat` should output to stdout by default, but if `--inplace` and `-o` are both left off of the command then the program fails with an error:
```
$ ocamlformat test.ml
ocamlformat: Must specify output file without --inplace
```

**Comment by jberdine** [comment]
Thanks for the report. Yes, the documentation is out of date. Outputting directly to stdout is not supported in order to implement the check that re-parsing the formatted code produces an equivalent parsetree. Output on stdout can be faked using a wrapper script such as [infer's](https://github.com/facebook/infer/blob/master/scripts/ocamlformat.sh).

**Comment by dbuenzli** [comment]
I'd really like to be able to `ocamlformat a.ml | diff - a.ml` to evaluate a bit how my style differs from the one you propose and it's a bit painful if each of us has to define our own wrapper script.

It doesn't seem too complicated to implement that inside the tool. Here's a [snippet of code](https://github.com/dbuenzli/cmdliner/blob/90974c1ebc0f0c04c21db8604915ed685aa2d5b8/src/cmdliner_manpage.ml#L427-L435) using only the standard library that will format to a temporary file to be deleted once the tool exits. Using this you can implement your check and then simply spit out its content of stdout.

**Comment by jberdine** [comment]
Ok, I'll stop being lazy about this. :-)

**Comment by hcarty** [comment]
Thank you!

**Comment by dbuenzli** [comment]
Thanks !
