### ISSUE TITLE
Bug: incorrect comment placement in commented list item

### ISSUE THREAD

**Issue by MisterDA** [ocaml-ppx/ocamlformat#2007]
I have a commented list item under the TODO. This is the diff that OCamlFormat created, you can see it moved the comment before the semi-colon finishing the previous list item, attaching the comment to the previous list item. This is incorrect in my case and I'd prefer to have the comment left out.

```diff
     Routes.
       [
         (s "pipelines" /? nil) @--> handle t (Parts.of_parts "");
-        (s "pipelines" /? wildcard) @--> handle t;
-        (* TODO: (s "artifacts" /? wildcard) @--> handle_artifacts;*)
+        (s "pipelines" /? wildcard) @--> handle t
+        (* TODO: (s "artifacts" /? wildcard) @--> handle_artifacts;*);
       ]
     @ R.extra_routes
```

**Comment by gpetiot** [comment]
I know this diff looks surprising, it's due to the `[_; ...]` lists not being built as `_ :: _` anymore (this is an `ocamlformat.0.20.0` change). The comments attached to each expression element are now formatted like any expression (there was some ad-hoc tweaking to handle comments in `::` expressions, as comments attached to the last element were attached to `[]`), which causes the trailing comment to wrap after the expression when it fits.
Sorry for the inconvenience but I don't think there is a way around this.
