### ISSUE TITLE
Bug: "margin not allowed here"

### ISSUE THREAD

**Issue by davesnx** [ocaml-ppx/ocamlformat#2254]
**Describe the bug**

The ocamlformat ppx doesn't allow margins, either top-level or per-expression. Example: 
```
let useLayoutEffect6 :
       (unit -> (unit -> unit) option)
    -> 'dependency1
       * 'dependency2
       * 'dependency3
       * 'dependency4
       * 'dependency5
       * 'dependency6
    -> unit =
 fun _ _ -> ()
 [@@ocamlformat "margin=200"]
```

I tried to look into issues and I couldn't find why, I know that type_dcl as well isn't allowd I would like to know why? and if it's expected?

Thanks and sorry if it's an annoying issue :(

**Comment by gpetiot** [comment]
Hi,

Yes it's expected. A few options are not allowed to be set "inline" (meaning in attributes, either attached to an element or global attributes) because we want their value to be the same for the whole run.

In the case of `margin`, the way it's handled by `Format` is also global (see: `Format.set_margin`), so we made the choice to handle it the same way.

**Comment by davesnx** [comment]
That makes total sense. I wouldn't open an issue if there was a slightly clearer message. Happy to add this to the error message myself.

**Comment by davesnx** [comment]
Closing this, since there's no bug
