### ISSUE TITLE
ocamlformat: syntax error

### ISSUE THREAD

**Issue by edwintorok** [ocaml-ppx/ocamlformat#23]
[These files](https://gist.github.com/edwintorok/da560c7522cf642965bccbd424ea9637/archive/e38ebc5988b7a6689dd5e7a5e1c042a624738b13.zip) fail to be reformatted with ocamlformat due to syntax errors.

`ocamlformat` was compiled with `4.05.0`, these files correctly compile when using the build system from their respective repositories with 4.04.2, and at first glance I don't see anything particularly wrong that'd make them fail on 4.05.0

**Comment by edwintorok** [comment]
Here is a smaller testcase from one of the files, looks like first class modules are problematic:
```ocaml
module type S = sig
  val x : unit -> unit
end

let get = failwith "TODO"

let foo () =
  let module X = (val (get) : S) in
  X.x ()
```

```sh
$ ocamlc -i syntax.ml
module type S = sig val x : unit -> unit end
val get : 'a
val foo : unit -> unit
$ ocamlc -i syntax.ml
module type S = sig val x : unit -> unit end
val get : 'a
val foo : unit -> unit
```

**Comment by jberdine** [comment]
Thanks! Yes, usually syntax errors are not due to parsing with a newer parser, but because the formatted code is just wrong.

**Comment by jberdine** [comment]
Thanks, this uncovered some bugs, which should be fixed in master now.

But there are some remaining issues with some of the files:
- ocamlformat basically requires code to not trigger warning 50 to work. For code that triggers warning 50, it is unlikely that ocamlformat will happen to preserve the docstring attachment.
- some files contain `with rpc` which does not parse. I guess that this is some camlp4 extension.
- similarly with `lwt`
- there are some expressions such as `{ response_of_request req hdrs with Http.Response.content_length = Some response_length }` which do not parse without adding parens around the record being updated. I'm not sure if this is a difference between versions of the ocaml parser, or maybe with the camlp4 parser.
- files that are sequences of toplevel phrases, as opposed to a module implementation or interface, are not supported by ocamlformat. It would be nice to support them, but there is no source location information in their parsetrees, so placing comments is impossible.
- some files contain `#include`, which does not parse.

It would be good to document these factors somewhere.

**Comment by edwintorok** [comment]
Thanks, sorry for not checking the files for `camlp4` and `cppo`, feel free to ignore those.
The file containing `{ response_of_request req hdrs with Http.Response.content_length = Some response_length }` has `syntax_camlp4o` so its not an `ocamlformat` bug.
