### ISSUE TITLE
Bug: AST diff around `pcd_vars`

### ISSUE THREAD

**Issue by alanechang** [ocaml-ppx/ocamlformat#2517]
The example program:

```ocaml
type _ g = MkG : 'a . 'a g;;
```

gets formatted into:

```ocaml
type _ g = MkG : 'a g
```

producing unequal ASTs:

```diff
19d18
<                   pcd_vars = 'a
```

`fmt_constructor_arguments_result` in `Fmt_ast` is the relevant function here. Wonder if we should keep `'a .` or opt to add some additional normalization logic.

**Comment by Julow** [comment]
Thanks for the report! This should be fixed by https://github.com/ocaml-ppx/ocamlformat/pull/2518

This is a quick and dirty fix, though. Ideally, we'd separate the code that recognize what form of constructor we're formatting and the code that formats it.
This is usually done in the `Sugar` module. Contribution welcome :)
