### ISSUE TITLE
Configure Travis to test older version of the compiler

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#262]
4.04 -> 4.07.

**Comment by jberdine** [comment]
I'm more worried about keeping the path clear to upgrading, rather than being dragged back by legacy versions. So I think that the main point is to be aware if the code takes a dependency on some part of compiler-libs that ocaml-migrate-parsetree does not version. So maybe just test the current and previous versions, perhaps trunk?

Given that ocamlformat parses code using the version of the frontend of the compiler used to build ocamlformat. The output of ocamlformat compiled with e.g. 4.04 can be different than that produced by the same ocamlformat compiled with 4.07. Since there are continual changes / improvements to the frontend, I'm not sure that it makes sense to try to test and support many versions.

**Comment by gpetiot** [comment]
I tend to agree with Josh on this, closing this issue since no one else commented on this.
