### ISSUE TITLE
Style option: never ident match cases

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-ppx/ocamlformat#265]
Something I grew quite fond in `ocp-indent` is to use the `strict_with=always` option this ensures that pattern match and `function` case definitions are never indented (sadly it does not do so on `type`definitions see [this issue](https://github.com/OCamlPro/ocp-indent/issues/183). This allows to take full advantage of your 80 columns and produce identifiable blocks of code without the typographic agitation of indentation.

**Comment by jberdine** [comment]
I'm not sure how common this style is, but submitting an option that does not complicate the code too much would be welcome. Note though that this sort of style, where the nesting of formatting boxes will need to be quite different from the nesting structure of the parsetree (because the indentation of the expression is not relative to the beginning of the expression) is quite involved and fragile in the current implementation.

**Comment by jberdine** [comment]
Easier after #406

**Comment by gpetiot** [comment]
The options `function-indent`, `match-indent`, `function-indent-nested` and `match-indent-nested` reproduce the behavior of the `with` and `strict_with` options of ocp-indent.
