### ISSUE TITLE
Whitespace in pattern matching

### ISSUE THREAD

**Issue by theindigamer** [ocaml-ppx/ocamlformat#28]
Looking at [this line](https://github.com/ocaml-ppx/ocamlformat/blob/beec55abfbd5a6b35827df39d08c869bd11274f3/src/Ast.ml#L439):

```
        | Pexp_constant _
         |Pexp_extension _
[...]
```

Discussing this on Reddit, I thought this is intentional (to note the fact that multiple guards give the same result), but another user pointed out that this might be a bug where "| " accidentally got replaced by " |"...

**Comment by jberdine** [comment]
This is intended, in order to visually indicate that there are multiple cases either with the same guard or body. This helps in cases where a are short body is mixed into a long pattern matching with some shared guards. For [example](https://github.com/ocaml-ppx/ocamlformat/blob/beec55abfbd5a6b35827df39d08c869bd11274f3/src/Ast.ml#L462-L464) in:
```
        | Pexp_tuple e1N | Pexp_array e1N -> assert (List.exists e1N ~f)
        | Pexp_construct (_, e) | Pexp_variant (_, e) ->
            assert (Option.exists e ~f)
```
the second line beginning with `| ` instead of ` |` indicates that the patterns on the first line are not covered by the body on the third line, but by their own body on the first line.

This is configurable: passing `--sparse` formats pattern matches without ever using ` |`, and instead always puts bodies on a new line.
