### ISSUE TITLE
Consider not opening a new window in emacs on error (file that doesn't compile)

### ISSUE THREAD

**Issue by loxs** [ocaml-ppx/ocamlformat#291]
I hit this quite often, as sometimes I go and fix a location and naively think that "all is OK", then issue `ocamlformat` just to discover that some other location in the file has an error.
When this happens, I get a new window opened to display the error, which is quite a big hassle to close and sometimes to reconfigure my previous state of windows.

Could we have some other, less disruptive way of reporting the error?

**Comment by jberdine** [comment]
Have you tried setting the `ocamlformat-show-errors` customization option, [here](https://github.com/ocaml-ppx/ocamlformat/blob/master/emacs/ocamlformat.el#L42)?

Note that the ocamlformat mode should send its output to `*compilation*`, see [here](https://github.com/ocaml-ppx/ocamlformat/blob/master/emacs/ocamlformat.el#L171). Do you repeatedly close the compilation buffer?

**Comment by loxs** [comment]
I just tried setting it to `echo` but it doesn't seem to work. When I manually call `M-x ocamlformat`, if there are errors in the ocaml file, nothing happens in the echo area. Which is still better than before though.

This gets written to the *Messages* buffer (I'm on Mac OS) :

```
Wrote /var/folders/wq/hh0gd3_57pschvmv66g839w40000gq/T/ocamlformatEYYYBU.ml
Could not apply ocamlformat
```

My setup is almost exactly this and I am not an emacs expert, so I don't know where to look further: https://github.com/ocaml/merlin/wiki/spacemacs-from-scratch

**Comment by jberdine** [comment]
The emacs integration [calls](https://github.com/ocaml-ppx/ocamlformat/blob/master/emacs/ocamlformat.el#L171) `get-buffer-create`, there is nothing about windows, only buffers. There must be something in your configuration that kills/hides `*compilation*` and that causes new buffers to create windows.

**Comment by jvillard** [comment]
Another observation: On syntax errors, ocamlformat brings up the compilation buffer with bright red messages. I then fix the errors, run ocamlformat again, but because it's not actually displaying anything in `*compilation*` under normal circumstances the buffer stays open and the errors stay there. At some later point in time I forget that the errors were fixed and I end up puzzled and with low self-esteem.

The `*compilation*` buffer is neat because one can jump to the error, but if errors were signalled some other way then one could still use merlin to jump to the syntax error when needed. (and in case of crashes, well, there's always `*Messages*` to debug)

**Comment by loxs** [comment]
> kills/hides *compilation* and that causes new buffers to create windows

I don't think so. The compilation buffer is always there and I can switch to it and it contains the last failed `ocamlformat` message. But if ocamlformat fails a second time, it doesn't add another message, but probably overwrites the whole buffer, that might constitute in "something" destroying it, before creating it again, but that something has to be triggered by ocamlformat just before issue-ing the new error.

I also have a buffer called `*Compile Log*`  where all the spacemacs compile messages go. `*compilation*` doesn't seem to be used by anything else other than ocamlformat.

**Comment by jberdine** [comment]
It is suboptimal that stale errors stay in the buffer. It would be bad to always clear the `*compilation*` buffer on success, however, since there are often useful compilation messages there. An improvement would be to detect if the current contents are an ocamlformat error and if so clear it on success. A PR implementing that would be welcome.

@jvillard, I don't know what you might mean by "if errors were signalled some other way", can you expand?

@loxs, I don't know why your emacs configuration causes new windows to be opened. I don't know what to suggest other than starting from plain emacs and gradually working out which part of your config causes this.

**Comment by jvillard** [comment]
@jberdine I was thinking of showing errors in the minibuffer (if that's the right name). This is where merlin displays messages such as type errors and the like. There's not a tremendous of space in there to show errors but when the error is too big I'm used to going to `*Messages*`.

**Comment by jvillard** [comment]
D'oh! that was the second comment in that thread...

When set to `echo`, I don't see the message when there is an error. It looks like an extra new line is printed when I look into `*Messages*`, maybe that's why. Also, if I run ocamlformat with `M-x ocamlformat` then it's even worse because I see "You can run the command ‘ocamlformat’ with <C-M-tab>" instead (but maybe there's nothing to do here).

In `*Messages*`:
```
Wrote /tmp/ocamlformat1584ypn.ml
Could not apply ocamlformat

```

I can open a separate issue for that if that's better.

**Comment by jberdine** [comment]
> Also, if I run ocamlformat with `M-x ocamlformat` then it's even 
> worse because I see "You can run the command ‘ocamlformat’ with " 
> instead (but maybe there's nothing to do here).

Add `(setq suggest-key-bindings nil)` to your emacs init to shut these 
messages up.

**Comment by jberdine** [comment]
See if https://github.com/ocaml-ppx/ocamlformat/pull/304 helps

**Comment by jvillard** [comment]
@jberdine 
> See if #304 helps

It does, thanks! Now I can see the last line "Applied ocamlformat" or "Could not apply ocamlformat".

**Comment by jberdine** [comment]
@loxs, #304 changes buffer handling in echo mode, maybe re-test?

**Comment by loxs** [comment]
Yes, it does, the same as for @jberdine

**Comment by jberdine** [comment]
Thanks. I'll close this, feel free reopen with more info if there are further issues.
