### ISSUE TITLE
Add option to use short local module open even when it costs indentation

### ISSUE THREAD

**Issue by avsm** [ocaml-ppx/ocamlformat#33]
```
-  Term.(term_result (const Phases.phase1 $ arch $ hub_id $ build_dir $ logs_dir $ setup_logs)),
-  Term.info "phase1" ~doc ~sdocs:Manpage.s_common_options ~exits ~man
+  ( (let open Term in
+    term_result
+      (const Phases.phase1 $ arch $ hub_id $ build_dir $ logs_dir $ setup_logs))
+  , Term.info "phase1" ~doc ~sdocs:Manpage.s_common_options ~exits ~man )
+
```

The following diff seems to be a case of succinct code being written to a longer form.  Specifically, the `Term.(term` now becomes a `let open Term in`, which is very verbose.  Is it possible to preserve the `M.()` module open syntax?

**Comment by jberdine** [comment]
This is hard since the two forms have the same representation in the parsetree. Currently what is done is the short form is used if the body fits on one line, and otherwise the long form is used to avoid extra indentation.

If there are ast patterns where the short form should always be used, that can be implemented. This is [currently done](https://github.com/ocaml-ppx/ocamlformat/blob/master/src/Fmt_ast.ml#L1060-L1063) for arguments of applications and constructors, for example. From the diff you quoted, I don't know the context here, but is the behavior you want something that could be expressed in a similar way to "always use the short form for application arguments"?

**Comment by alainfrisch** [comment]
> This is hard since the two forms have the same representation in the parsetree.

@jberdine Don't hesitate to propose PRs to keep more such "syntactic details" in the official Parsetree, once you have a good idea of which ones make sense (based on user requests).
