### ISSUE TITLE
Add presets config similar to ocp-indent.

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#357]
Here is what they do in ocp-indent: https://github.com/OCamlPro/ocp-indent/blob/4830ebf5d1c1b8f47bc152ff13d2c6aa1aad705b/src/indentConfig.ml#L51

I'll like to be able to define a preset config for janestreet, currently hardcoded here:  https://github.com/janestreet/ocamlformat/blob/jane/src/Conf.ml#L813

**Comment by jberdine** [comment]
I think that there are two things going on here:
1. packaging sets of config settings into single styles
2. defining those aggregate styles in source code

To me, 1. is clearly desirable. But I'm not sure about 2. Is it seen as a feature that e.g. to change the definition of the style, using a new version would be needed?

**Comment by hhugo** [comment]
I d like to collect feedback from @AltGr about the setup in ocp-indent

**Comment by samoht** [comment]
As far as I know, most of the people use the default profile for ocp-indent (with some level of tweaks via local `.ocp-config` from power users). Janestreet has its own `ocp-indent` profile which is set in stone since the few initial iterations. And the "beginner" profile is used by `ocamltop`, but I am not sure that was such in a good idea.

IMHO, like in ocp-indent having sensible good default is the priority, and a few profiles corresponding to the code style of large industry users (as long as they don't change too often, and they usually don't :-) )

**Comment by jberdine** [comment]
Ok, it sounds like it makes sense to at least start out by hardcoding the definitions of the styles. If it becomes an issue, supporting defining styles in config files can be done later.
