### ISSUE TITLE
Not breaking after bind/map operators

### ISSUE THREAD

**Issue by samoht** [ocaml-ppx/ocamlformat#359]
Currently, `>>=` and `>|=` seems to always be put on a newline:

```ocaml
f x >>= fun y ->
g y >>= fun () ->
...
```

is reformated as

```ocaml
f x
>>= fun y ->
g y
>>= fun () ->
...
```

Would it be possible to not do that using an option?

**Comment by jberdine** [comment]
Currently `>>=` etc. are formatted using the same code path as for general binary operator applications, which places the operators at the beginning of lines when it is necessary to break.

To achieve this suggested style, a special case for `bind`-like operators could be added to `fmt_expression` in `Fmt_ast`, to be used instead of [this](https://github.com/ocaml-ppx/ocamlformat/blob/990dda59a17dde1151e37ed0f862196ba909eb99/src/Fmt_ast.ml#L1441).

One consideration is how to choose which operators to use this special case for. Just `>>=` and `>>|`? Some configurable set? Any binop applied to a `fun`(`ction`) 2nd arg? The first option seems unfair to any code that uses its own monadesque or cps combinators. Maybe the last is ok. It would be nice not to need much configuration. Thoughts?

**Comment by gpetiot** [comment]
Closed with #463

**Comment by vphantom** [comment]
@gpetiot Is there a specific combination of configuration options to use in order to keep `expr >>= fun arg ->` groups each on one line?  I'm not getting that behavior with ocamlformat v0.9 `--profile=janestreet -m 80`:

```ocaml
let f_test_noppx () =
  somefunction 10000000 20000000
  >>= fun a -> somefunction 20000000 a >>= fun b -> Ok (b + 42)
;;
```

I'm trying not to use `let%bind` in the name of simplicity in a project which strictly uses ocamlformat, but the above isn't very intuitive compared to the widely used structure:

```ocaml
let f_test_noppx () =
  somefunction 10000000 20000000 >>= fun a ->
  somefunction 20000000 a >>= fun b ->
  Ok (b + 42)
;;
```

**Comment by gpetiot** [comment]
You should try `--no-break-infix-before-func`.

**Comment by vphantom** [comment]
Thanks for the hint!  I get the following, which is very readable:

```ocaml
let f_test_noppx () =
  somefunction 10000000 20000000 >>= fun a ->
  somefunction 20000000 a >>= fun b -> Ok (b + 42)
;;
```

Just curious: I don't suppose there's a rule which would allow me to break after that second `->` even though the final expression is short?

**Comment by gpetiot** [comment]
I don't think there is such option so far. Feel free to open an issue to gather opinions about it, and maybe someone will work on it :)
