### ISSUE TITLE
-o /dev/null fails

### ISSUE THREAD

**Issue by emillon** [ocaml-ppx/ocamlformat#398]
Hi,

The following happens when I'm trying to output to `/dev/null`:

```
 % touch empty.ml
 % ocamlformat empty.ml -o /dev/null
ocamlformat: Cannot process "x.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: unhandled exception.
```

Hooking up `strace` it seems that it's trying to open many files in `/dev`.

While I don't really need `-o /dev/null` to work, I'm a bit surprised by this behaviour. Is there a reason why the tempfiles are not written in `/tmp` (or `$TMPDIR`)?

Thanks!

**Comment by jberdine** [comment]
The temp files are created in the same directory as the final output file because commonly the tmp directory is on another file system and so renaming the final temp file to the output fails, or else there is a spurious expensive copy to do.

Would outputting to stdout and redirecting it with `ocamlformat foo.ml -o - > /dev/null` work for your use case?

**Comment by emillon** [comment]
I don't need specifically `-o /dev/null` to work, but the error message prompted me to report it, I did so :)

I think it'd be enough to be a bit more specific in the error message, like "cannot write temporary file /dev/x28398.ml" for example?
