### ISSUE TITLE
Performance issue with very large list literal  

### ISSUE THREAD

**Issue by hhugo** [ocaml-ppx/ocamlformat#409]
see https://github.com/janestreet/core/blob/master/test/bin/ofday_unit_tests_v1.ml

Turning the list into an array improves performances a lot.

**Comment by gpetiot** [comment]
Do you have any idea about where to start?

**Comment by hhugo** [comment]
I would actually lower the priority of that one. I've seen only two problematic files in the entire opam repo

**Comment by jberdine** [comment]
Maybe it's clear, but note that it is reasonable for the perf to change a lot with an array vs a list since internally lists are deeply nested applications rather than a flat aggregate.

As for where to start, I would first see if anything stands out in the data that can be collected by linux `perf`. Even just running `sudo perf top` while processing the input file triggering the slow formatting could be useful.

**Comment by gpetiot** [comment]
In #823 I made the sugaring functions tail-recursive but it doesn't improve the performance.
So the performance issue is actually not in Sugar.list_exp but in Ast.is_sugared_list.
I tried several approaches to optimize the latter:
- using exceptions didn't improve the performance
- assuming a list is always sugared or unsugared breaks the ast

**Comment by hhugo** [comment]
One more optimization in https://github.com/ocaml-ppx/ocamlformat/pull/833
