### ISSUE TITLE
Ambiguous sequence

### ISSUE THREAD

**Issue by mbouaziz** [ocaml-ppx/ocamlformat#423]
```
let () = r := fun () -> f () ; g ()
```
looks ambiguous to me and could mean
```
let () = (r := fun () -> f () ); g ()
```
or
```
let () = r := fun () -> (f () ; g ())
```
or even (but types prevent it in my case)
```
let () = r := ((fun () -> f () ); g() )
```

**Comment by trefis** [comment]
> looks ambiguous to me and could mean

Nah, it couldn't. :)

More seriously, the remark makes sense (although the *correct* way to add parentheses in this case is `r := (fun () -> f (); g ())`), but the extra parentheses will be annoying as soon as you write something in monadic style.
I guess the heuristic to decide whether or not to add superfluous parentheses could be "does the function fit on a single line?".
If yes, add the parentheses, otherwise, indentation will make the scoping clear anyway?
