### ISSUE TITLE
indentation quirks

### ISSUE THREAD

**Issue by hannesm** [ocaml-ppx/ocamlformat#43]
thank you for developing ocamlformat.  I ran it on some source of mine, and struggle with the diff below (esp. ocamlformat (v0.2) disagrees with ocp-indent (1.6.1):

```
 let is_hostname t =
   (* TLD should not be all-numeric! *)
-  (if Array.length t > 0 then
-     String.exists Char.Ascii.is_letter (Array.get t 0)
-   else true) &&
-  Array.for_all check_host_label t
+  ( if Array.length t > 0 then String.exists Char.Ascii.is_letter t.(0)
+  else true )
+  && Array.for_all check_host_label t
```

I'd expect the `else` to be indented 4 spaces (instead of the 2).

**Comment by jberdine** [comment]
In general, ocamlformat is not intended to produce the same indentation as ocp-indent. It seems that it would be useful in some workflows to include an option to do so, but I expect it to be non-trivial and it is not something that I will spend the time to implement.

Regarding the indentation of `else` in this particular case. It would be a much less involved pull request to add an option to indent parenthesized `else` clauses from the `if` instead of the opening paren.

**Comment by hannesm** [comment]
the same happens for `( match ...` where the individual cases are not indented for 2 more spaces (for `(`).

**Comment by jberdine** [comment]
The reasoning behind these cases is about being economical with indentation. That is, in cases where an expression/pattern/etc is parenthesized, breaks across multiple lines, and will have the actual user code (that is, not keywords and syntactic elements such as `|`) within indented anyhow, then the indentation is not increased just because of the parens. A rough goal is to have the high-level structure be clear by looking at the left margin, and to minimize indentation subject to that. Note that the current approach to indentation is not independent of how infix operators are formatted at the beginning of lines instead of at the end of the preceding line. This has been tested on only so much code though, and there are likely bad cases.

Cases where the formatting is "unfamiliar" are expected, but I would like to hear about cases where the formatting is misleading.

**Comment by jberdine** [comment]
Closing since matching ocp-indent is not a goal. Please open issues for cases where the formatting obscures the syntactic structure, etc. And anyone is welcome to open an issue if planning a serious effort to implement an ocp-indent matching mode.
