### ISSUE TITLE
indentation in pattern matches

### ISSUE THREAD

**Issue by hannesm** [ocaml-ppx/ocamlformat#44]
I use ocamlformat v0.2 and ocp-indent 1.6.1 (both without any custom configuration), both inside of emacs.  My expectation is that they agree upon indentation in pattern matches.  The following diff is a bit disappointing:

```
     match Cstruct.get_uint8 buf off with
     | 0 -> Ok ((`Z, off), offsets, succ off)
-    | i when i >= ptr_tag -> (* 192 is 1100_0000 which is the pointer tag *)
-      let ptr = (i - ptr_tag) lsl 8 + Cstruct.get_uint8 buf (succ off) in
-      Ok ((`P ptr, off), offsets, off + 2)
-    | i when i >= 64 -> Error (`BadTag i) (* bit patterns starting with 10 or 01 *)
-    | i -> (* this is clearly < 64! *)
-      let name = Cstruct.to_string (Cstruct.sub buf (succ off) i) in
-      aux ((name, off) :: offsets) (succ off + i)
+    | i when i >= ptr_tag ->
+        (* 192 is 1100_0000 which is the pointer tag *)
+        let ptr = (i - ptr_tag) lsl 8 + Cstruct.get_uint8 buf (succ off) in
+        Ok ((`P ptr, off), offsets, off + 2)
+    | i when i >= 64 ->
+        Error (`BadTag i) (* bit patterns starting with 10 or 01 *)
+    | i ->
+        (* this is clearly < 64! *)
+        let name = Cstruct.to_string (Cstruct.sub buf (succ off) i) in
+        aux ((name, off) :: offsets) (succ off + i)
```

I'm not sure how other people use ocamlformat, but I thought of it as a pre-commit hook for my git repository.  is there a way to use it instead of ocp-indent for writing code?  if not, I can see two solutions for this:  provide a `.ocp-indent` which has the same behaviour of ocamlformat regarding indentations; or modify ocamlformat to match the default ocp-indent.

**Comment by jberdine** [comment]
A workflow I use is to use ocp-indent while editing a file and it is in a state where it does not yet parse. I have a key bound to the `ocamlformat` emacs function defined in `ocamlformat.el` that I use once the file parses. Files can be formatted when saving by setting `(add-hook 'before-save-hook 'ocamlformat-before-save)`.

It has not been a design objective for ocamlformat and ocp-indent to agree on indentation. It might be possible to define a set of configuration options to achieve this. I would expect that getting this to really work would be difficult since ocamlformat operates from the abstract syntax tree and ocp-indent uses patterns over the concrete syntax.

**Comment by jberdine** [comment]
Closing since the emacs configuration suggestion is in the README.md and matching ocp-indent is not a goal. Please open issues for cases where the formatting obscures the syntactic structure, etc. And anyone is welcome to open an issue if planning a serious effort to implement an ocp-indent matching mode.
