### ISSUE TITLE
more newlines: between top-level `let` bindings vs modules

### ISSUE THREAD

**Issue by hannesm** [ocaml-ppx/ocamlformat#46]
The following diff is also surprising:
```
   let str = to_string t in
   of_string_exn ~hostname:false (String.Ascii.lowercase str)
 
+
 (*BISECT-IGNORE-BEGIN*)
 let pp ppf xs = Fmt.string ppf (to_string xs)
+
 (*BISECT-IGNORE-END*)
 
-module IntMap = Map.Make(struct
-    type t = int
-    let compare : int -> int -> int = compare
-  end)
+module IntMap = Map.Make (struct
+  type t = int
+
+  let compare : int -> int -> int = compare
+end)
 
 let compare_sub a b =
   String.compare (String.Ascii.lowercase a) (String.Ascii.lowercase b)
 
+
```

it seems that after `let` bindings there are two newlines, but an (interleaved) `module` definition ends with a single newline... also a `let` binding on a single line ends with only a single newline.

I personally prefer to have only a single newline after a let binding, but am open to use whatever is default, as long as the amount of newlines after each binding is consistent.

**Comment by jberdine** [comment]
At one point earlier in development there were only single open lines following multi-line let bindings.  For some code that worked fine, in particular for code that was reasonably "sparse" and did not have e.g. function definitions with many consecutive lines that reached close to the margin interspersed with some short lines. But for code that is not so sparse, having only one open line between let bindings was often not very legible. So far I have not seen serious problems with code getting so dense as to hurt legibility due to only single open lines following modules, probably due to the visual "lightness" of `end`. I have not experimented with also using two open lines in these cases, but it might well work better.

This is a point where contributing an option to only use one open line would be useful to see which style people gravitate to over time.

Getting the spacing around comments "right" is just hard.

**Comment by hannesm** [comment]
@jberdine thank you for your explanation.  the solution in ocamlformat is fine given the reasoning, I was only surprised a bit by the "inconsistency" of the number of newlines, but am happy to adapt to that behaviour.

I fear if you add style options to ocamlformat, people will start using them (and you need to maintain them).  I'd rather have a well-thought style by default and explain this to people (as you did in this issue).

**Comment by jberdine** [comment]
I agree that it is best to have a good default, but syntax can be very personal, and there are some strong opinions around. I think that it would be unfortunate if a project chooses not to use auto-formatting simply because the auto-formatter tyrant refuses to accept contributions of config options that make the style acceptable to a given project. I realize that adding config options can be a cop out to avoid the work of finding good and widely applicable defaults, but I don't want to be that tyrant, and I don't really want to arbitrate over potentially endless syntactic bike-shedding either. If someone feels strongly enough to submit a pull request implementing a config option for an alternate code style, and the community gravitates to switching it on, then that is strong evidence that the default is suboptimal.

Another point is that one strength of using an auto-formatter is that when a better style is found, it can easily be automatically applied to existing code (subject to the cost of churning source control history). I don't expect that it is possible to get the syntax style right (whatever that means) on the first try, and think that there is value in the possibility of exploring alternatives.
