### ISSUE TITLE
Position of 'in' keyword for multiline bindings

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#506]
Currently if a binding can't fit on one line, the `in` keyword is written alone on a line:
```
    let pair (Arg (trm_x, set_x)) (Arg (trm_y, set_y)) =
      let trm_xy = Term.(const (fun a b -> (a, b)) $ trm_x $ trm_y) in
      let set_xy (a, b) = set_x a ; set_y b in
      Arg (trm_xy, set_xy)
    in
    ...
```

Another option would be to let it at the end of the body:
```
    let pair (Arg (trm_x, set_x)) (Arg (trm_y, set_y)) =
      let trm_xy = Term.(const (fun a b -> (a, b)) $ trm_x $ trm_y) in
      let set_xy (a, b) = set_x a ; set_y b in
      Arg (trm_xy, set_xy) in
    ...
```

**Comment by jberdine** [comment]
I implemented this very early on, but it was problematic because it sometimes caused confusion. In situations where the body of the `let` is long(er), and the indentation of the body varies, especially if it is deep near the end, it can be very difficult to quickly visually identify the point where the indentation reduces to the level of the `let`. People would end up putting the cursor on the `let` and scrolling down to find the end. Placing the `in` on the left resolved these problems. This is a case where formatting manually one would be able to choose which position to use for the `in` based on human understanding, but the formatter cannot be so clever. It has not seemed worth it or a good idea to devise a heuristic to decide when to use one form vs the other.

An option could be added, but it seems superfluous and I'd like to see a compelling argument before anyone spent time implementing it, and adding code complexity to maintain.
