### ISSUE TITLE
Shebang triggers syntax error

### ISSUE THREAD

**Issue by mwgkgk** [ocaml-ppx/ocamlformat#523]
Code:
```ocaml
#!/usr/bin/env ocaml

(* ... *)
```
Error:
```shell
ocamlformat: ignoring "hello.ml" (syntax error)
File "hello.ml", line 1, characters 0-3:
Error: Syntax error
```
Judging by this StackOverflow post [recommending preprocessing the shebang away with sed](https://stackoverflow.com/a/7616621) these things are not super welcome in OCaml community. Github search [returns a number of examples](https://github.com/search?q=%22%2Fusr%2Fbin%2Fenv%22++language%3AOCaml&type=Code), some of them including the top-level directives like `#load` which trigger the same syntax error. I'm too new to be sure if these examples fall under the TOS listed in the readme _("OCamlFormat requires source code that meets the following conditions...")_ . Preprocessing the thing away with sed would require to stitch it back on again :)

**Comment by jberdine** [comment]
I wouldn't say that this is unsupported because of being unwelcome, but just because ocamlformat does not do any processing of the input file before asking the compiler to parser it. The `ocaml` toplevel system has a special case to ignore initial `#!` lines, but the parser itself does not.

Unlike preprocessing, this is probably simple enough that ocamlformat could be reasonably extended to handle it.

**Comment by ccqpein** [comment]
I find same error when I put `#require "Pkg"` in `.ml` file. I just start to learn ocaml, so I run it in `utop -emacs`, and I put `#require "Pkg"` in source file directly. emacs support looks good, It should be nice if ocamlformat can support `#` keywords.

**Comment by hhugo** [comment]
ocamlformat currently support directives (`#require "Pkg"`) for files with `.mlt` extension.
