### ISSUE TITLE
Don't use literal formatting

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#577]
In order to make the debugging easier and make possible the (future) abstraction of that code, do the following changes (and define the Fmt functions if necessary):
- use `Fmt.break x y` instead of `@;` and `@;<x y>`
- use `Fmt.space` instead of `@_` (space instead of the underscore)
- use `Fmt.cut` instead of `@,`
- use `Fmt.newline` instead of `@\n`
- use `Fmt.open_box` instead of `@[` (with the appropriate box type)
- use `Fmt.close_box` instead of `@]`

**Comment by jberdine** [comment]
This will have a huge effect on the source, I suspect making it more difficult to read. I'm not sure it's the right approach. There are so many break hints that when debugging something in particular, it may well be more efficient to add some output to the hints of interest rather than being bombarded with them all.
