### ISSUE TITLE
Break in function type annotation

### ISSUE THREAD

**Issue by Julow** [ocaml-ppx/ocamlformat#620]
Current formatting:

```
let vexpr (type visit_action) : ('a, 'result, visit_action) context -> 'a -> visit_action
    = function
  | Local -> fun _ -> raise Exit
  | Global -> fun _ -> raise Exit
```

Expected:

```
let vexpr (type visit_action)
    : ('a, 'result, visit_action) context -> 'a -> visit_action =
  function
  | Local -> fun _ -> raise Exit
  | Global -> fun _ -> raise Exit
```

**Comment by gpetiot** [comment]
Here is the current output on master:    (the indent of `= function` has been moved to the left)
```ocaml
let vexpr (type visit_action) : ('a, 'result, visit_action) context -> 'a -> visit_action
  = function
  | Local -> fun _ -> raise Exit
  | Global -> fun _ -> raise Exit
;;
```

If the type is longer we get:
```ocaml
let vexpr (type visit_action)
    : ('a, 'result, visit_action) context -> 'a -> visit_action -> 'a -> visit_action
  = function
  | Local -> fun _ -> raise Exit
  | Global -> fun _ -> raise Exit
;;
```

I thought having `=` on a new line was the expected behavior for the janestreet profile when the parameters and the type fit on the same line, are we sure we want to change this? @hhugo

**Comment by hhugo** [comment]
I agree with @gpetiot. I think we expect to have `=` at the beginning of the line in that case.
@mbarbin ?

**Comment by mbarbin** [comment]
Agreed with @hhugo and @gpetiot.  Seems OK to go with what master does as shown in @gpetiot's example.  Looks good, thanks!
