### ISSUE TITLE
Splitting pipeline operators on newlines

### ISSUE THREAD

**Issue by lpil** [ocaml-ppx/ocamlformat#69]
Hello! First of all thank you for this tool, I'm very much enjoying it.

I like to use a pipeline operator in order to structure my code so that it reads from left to right (similar to F#, Elm, Elixir, ReasonML etc)

```ocaml
let ( |> ) x f = f x
```

When using this ocamlformat wraps long lines like so:

```ocaml
let sum_of_squares num =
  num + 1 |> List.range 0 |> List.map ~f:square
  |> List.fold_left ~init:0 ~f:( + )
```

It's more commonly formatted like so:

```ocaml
let sum_of_squares num =
  num + 1 
  |> List.range 0 
  |> List.map ~f:square
  |> List.fold_left ~init:0 ~f:( + )
```

Is it possible to get a format closer to this, with one function on each line? Alternatively is there another operator that I could to get this style?

Thanks,
Louis

**Comment by jberdine** [comment]
Currently `|>` is treated just like any other infix operator, so one question is whether this suggestion to always break is exclusively about `|>` or should apply to some/all other infix operators as well?

Note that the current implementation tries to ensure that the cases which are not broken are both short and simple in an attempt to avoid generating difficult to read code. I would be very interested to see examples of real code where this fails.

I would be happy in principle with a PR that added a config option to always break `|>`.

I'm more hesitant about changing the default, since it isn't clear to me why current problems with `|>` won't be equally applicable to user-defined operators (such as those defined and used extensively in ocamlformat itself). It would be better to see examples of hard to read formatting and fix the issue in general. Note that I think there are two distinct situations, one where the current output is "ok" but unconventional or otherwise not the desired style, in which case adding a config would be preferred. In the other case, where the current output is objectively hard to read, it would be better to fix the underlying problem.

**Comment by lpil** [comment]
I agree with your reasoning.

I'm new to OCaml but interested in contributing this feature if I find time. If I open a PR with a first iteration would you be happy to provide feedback and guidance? I'm sure my code isn't very idiomatic yet :)

Thanks,
Louis

**Comment by jberdine** [comment]
I'm very happy to give feedback, etc. on PRs! One thing to keep in mind, at least initially, is that it's usually best to err on the side of submitting too early and too often. :-) This is especially important since there is essentially no test suite.

**Comment by lpil** [comment]
Oh dear! I feel a little less brave now

**Comment by jberdine** [comment]
Well, `make -C test test` will clone infer and check that it reformats correctly, but that is one style of code.

**Comment by cfcs** [comment]
Am I the only one who would prefer a hybrid of these, "wrap if the line becomes too long, but indent"?
ie:
```
let sum_of_squares num =
  num + 1 |> List.range 0 |> List.map ~f:square
          |> List.fold_left ~init:0 ~f:( + )
```

**Comment by lpil** [comment]
The behaviour in used to in other formatters is that either the operators are all on one line, or every operator in the chain have a newline before them.

**Comment by jberdine** [comment]
@cfcs, I expect you're not alone, but note that currently ocamlformat almost never indents based on something of variable width. That is, the amount of indentation change from one line to the next is some small constant like 1, 2, or 4 spaces. So such a style would probably be not very uniform without many other changes. Also, would you indent the second line no matter how long the first argument is? If not, how long is it allowed to get? I don't know how to resolve this sort of question reliably with an algorithm.

@lpil, that is another option that has the attractive property of being very predictable. There is code which would get excessively long vertically, so it would be good to have as a config option.

**Comment by cfcs** [comment]
@jberdine I think I would personally split if it's "too complex", ie if there are more than ~3 non-whitespace, non-`()` lexemes, but I appreciate that's a matter of taste.

In any case, no matter what the consensus ends up being, I would argue against having too many movable parts in the form of configuration options - at least the uniformity of having "one proven way to do it" is the main appeal something like `ocamlformat` has for me.

**Comment by jberdine** [comment]
@cfcs, there is some form of "too complex" already in the [is_simple](https://github.com/ocaml-ppx/ocamlformat/blob/master/src/Ast.ml#L493) function. It's definition is in no way canonical, just evolved to its current definition by looking at cases which were "too complex" without getting too complicated to implement. Proposals for alternatives would be welcome, but it might be hard to come  to one universally-agreed definition.
