### ISSUE TITLE
poor formatting of toplevel directives

### ISSUE THREAD

**Issue by jberdine** [ocaml-ppx/ocamlformat#731]
toplevel directives are formatted with leading `;;`, and moved wrt comments:

```
$ ocamlformat --name tools/gen_version.mlt tools/gen_version.ml
;;
#directory "+unix"

;;
#load "unix.cma"

(**********************************************************************
 *                                                                    *
 *                            OCamlFormat                             *
 *                                                                    *
 *  Copyright (c) 2019-present, Facebook, Inc.  All rights reserved.  *
 *                                                                    *
 *  This source code is licensed under the MIT license found in the   *
 *  LICENSE file in the root directory of this source tree.           *
 *                                                                    *
 **********************************************************************)

let fake_watermark = "%%" ^ "VERSION" ^ "%%"
```

**Comment by jberdine** [comment]
revert #732 when this if fixed

**Comment by hhugo** [comment]
Should be improved once we switch to 4.08 https://github.com/ocaml-ppx/ocamlformat/issues/630
thanks to the following PR on the compiler.
```
GPR#1954: Add locations to toplevel directives
```

**Comment by hhugo** [comment]
fixed by #831

**Comment by frou** [comment]
Are the spaced out directives with the double-semis here to stay? With ocamlformat v0.15, that behaviour remains the same as the original report mentioned.

**Comment by gpetiot** [comment]
I think this issue relates to the directives' comments not being correctly attached to the right item (should be attached to the first directive but since there wasn't any location attached to the directive in the ast back then it was attached to the first item having a location, which is the let binding).
There is #1389 that refers to the `;;` item spacing, but this is not as easy to fix as it sounds, I will open a PR when this is ready

**Comment by frou** [comment]
@gpetiot Alright - Thank you, I appreciate it
