### ISSUE TITLE
Possible edge case

### ISSUE THREAD

**Issue by chrismamo1** [ocaml-ppx/ocamlformat#776]
Trying to use ocamlformat on a large project, I've started getting this error message:

```
ocamlformat: Cannot process "redacted.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: ast changed.
```

I've whittled the problem down to a rather specific-looking case:

```
let%any_extension f = function()
  | _ -> ()
```

Basically, any time a top-level `let`-extension defines a `function`. Am I doing something obviously wrong?

**Comment by chrismamo1** [comment]
I'm doing this for my job, so I'm quite motivated to fix the problem, but I'm totally unfamiliar with this project. If a developer could point me in the right direction then I'll certainly try to fix the issue.

**Comment by jberdine** [comment]
Thanks for your interest!

I suspect the bug is that the extension is formatter [here](https://github.com/ocaml-ppx/ocamlformat/blob/master/src/Fmt_ast.ml#L3807) and then the body is formatted without clearing the extension [here](https://github.com/ocaml-ppx/ocamlformat/blob/master/src/Fmt_ast.ml#L3800). Probably `?ext` in the second one should be removed.

**Comment by chrismamo1** [comment]
I've just encountered a similar issue that doesn't appear to have such a straightforward fix. I get the error `BUG: generating invalid ocaml syntax.` for this file:

```
type%any_extension t =
  < a: 'a >
```
