### ISSUE TITLE
Cannot find explanation on how to use the formatter

### ISSUE THREAD

**Issue by av737** [ocaml-ppx/ocamlformat#78]

**Comment by jberdine** [comment]
First, no need to clone in order to install, just execute `opam install ocamlformat`. See the [README](https://github.com/ocaml-ppx/ocamlformat#installation).

Once installed, execute `ocamlformat --help` for usage instructions. At the simplest, execute `ocamlformat -i your_file.ml` to reformat `your_file.ml` in-place.

Editor integration may be more involved. The README sketches the necessary emacs config, but integration for other editors is not builtin.

Optimistically closing, but please reopen if there are further questions.
