### ISSUE TITLE
More "word separator" characters while splitting strings

### ISSUE THREAD

**Issue by smondet** [ocaml-ppx/ocamlformat#79]
The new string wrapping in `master` is really cool.

I noticed that sometimes very long strings in code can be paths/URIs, like:

```ocaml
  let default_css =
    "https://bootswatch.com/3/bower_components/bootstrap/dist/css/bootstrap.min.css"
```

It'd be nice to be able to add `/` as a word separator for instance.

**Comment by jberdine** [comment]
Allowing more separators sounds useful. I wonder whether it makes sense to hard-code more than just whitespace, or to add a config option. Thoughts?

**Comment by gpetiot** [comment]
> Allowing more separators sounds useful. I wonder whether it makes sense to hard-code more than just whitespace, or to add a config option. Thoughts?

I don't know if there is a lib we can rely on to tell us whether a string is a syntactically valid URI or URL or file path, so that we can split on `/` (or `.` or `@` depending on the protocol or what is most used in the string). But it wouldn't hurt to add an option before we can come up with a good heuristic for this.
