### ISSUE TITLE
Feature request: gradually including rules 

### ISSUE THREAD

**Issue by ryanrhymes** [ocaml-ppx/ocamlformat#882]
Hi,

We have been trying to adopt ocamlformat into Owl to enforce the consistent coding style. However, Owl has a rather big codebase and we would like to gradually include individual style rule one by one to minimise the impact on several parallel work.

By default, ocamlformat applies all the rules if an empty `.ocamlformat` is passed in. Is there a mechanism so that we only apply the rules which have been defined in `.ocamlformat` but leave the undefined rules disabled? 

Many thanks. Refer to https://github.com/owlbarn/owl/pull/416

**Comment by gpetiot** [comment]
Unfortunately ocamlformat doesn't work this way, it is not a set of rules that you can enable/disable that are applied on the existing code. Instead, it prints the OCaml code from the AST, and the options are some minor variations of the way some nodes/constructs are printed.

So we can't disable an option, as each node has to be printed in a certain way anyway (hypothetically every option could have a `preserve` value, but I'm not sure it's even feasible for some options, and we have plans to rely less and less on the concrete input code anyway, because in some cases it makes ocamlformat take longer to reach a fixpoint).

**Comment by ryanrhymes** [comment]
OK, I see. Thanks for the explanation. Then having a comprehensive set of options for fine-grained control seems to be an option. Of course, we can also apply ocamlformat to some owl source files in the beginning then include more files gradually.

**Comment by gpetiot** [comment]
Exactly, you have to find the more optimal set of options that minimize the diff with the current state of codebase. And if a new option would be useful for you, feel free to open a new issue (by the way I took care of the type/match cases horizontal alignment earlier today)
