### ISSUE TITLE
Do not fail on incorrect files

### ISSUE THREAD

**Issue by gpetiot** [ocaml-ppx/ocamlformat#906]
Files that cannot be fully parsed like:
```ocaml
let fooooooooooo =
  let a = 1 in
  let fooooooooooooooo =
    let b = 2 in
    let foooooooooooooo =
```
should be processed by `ocamlformat` (like it is the case with `ocp-indent`).

No pressure yet, but it would be a killer feature for 1.0

cc @let-def, any new insights since the last time we discussed about it is welcomed.

**Comment by emillon** [comment]
Hi,

Summarizing an offline discussion with @let-def & @gpetiot, the plan looks like this:

We use a parser that can do recovery at the structure item level. This means that it is able to "skip" until the end of a structure item. A special extension is then inserted into the resulting AST. For other (valid) structure items, the output is a normal AST.

Then, when formatting the AST, there's a special case for extensions that correspond to invalid fragments: `ocamlformat` outputs the verbatim string that's present in the original source code. For valid parts, it continues to work as when the whole file is valid.

Here's an example. Suppose the input file looks like this:

```ocaml
let f x =
  2 * x

let g x =
  let z = 3 in

let h x =
  print_endline x
```

First step: the recovery parser does its job, and as all the heuristics necessary to detect that the middle part is missing an expression at the end. It creates an expression (say, `()`) to insert it in the right place and to get to a state where the structure item is over (Note: this is hard. In this example, it's also possible to continue parsing by considering that `let h` is a second `let-in` binding. It is possible to use the amount of leading whitespace to determine what to do). Since the parser tracks the position in the source file it's able to return the ignored part as a payload. The output AST corresponds to:

```ocaml
let f x =
  2 * x

[%ocamlformat.invalid_structure_item "let g x =\n  let z = 3 in"]

let h x =
  print_endline x
```

Next step: let's format this. The top and bottom structure items go through the normal algorithm. The middle one is printed verbatim (maybe we need to tell the box algorithm to pretend that it's 0 characters wide so that it cannot change the layout of the other parts). So, the result is:

```ocaml
let f x = 2 * x

let g x =
  let z = 3 in

let h x = print_endline x
```

Job done!

Structure items are a nice first boundary, maybe later we can go deeper into expressions, but it seems much harder.

**Comment by jberdine** [comment]
Just for discussion, are the structure items here expected to be toplevel implementation file elements, or should structure items in the body of a functor be treatable in the same way?

**Comment by emillon** [comment]
Structure items in the body of a functor (or other similar structure items, say bodies of `let module in`) should in theory work in a similar way; but the recovery heuristic might work better for toplevel ones. We'll discover that when experimenting :)

In practice, if that does not work too well, we can start by supporting toplevel ones only.
